### ISSUE TITLE
为什么switch 点选会出现个背景颜色呢？

### ISSUE THREAD

**Issue by travelCN** [nutui-uniapp/nutui-uniapp#101]
### nutui-uniapp 版本号

1.3.0

### 平台

weapp

### 重现链接

无

### 重现步骤

直接在小程序例子里，在全局配置里，一个是开关，一个是评分。点击会有背景色
新: 返回顶部backtop也有这个情况

### 期望的结果是什么？

无背景色

### 实际的结果是什么？

无背景色

**Comment by yang1206** [comment]
模拟器的问题，真机不会有

**Comment by travelCN** [comment]
我真机有啊。就是例子扫码真机才看到的啊。

**Comment by yang1206** [comment]
> 我真机有啊。就是例子扫码真机才看到的啊。

我这里没有发现，可以提供一个截图或者视频吗

**Comment by travelCN** [comment]
https://github.com/nutui-uniapp/nutui-uniapp/assets/15223877/3611a170-b86e-4e53-b2d0-bb9b8839c145

**Comment by travelCN** [comment]
https://nutui-uniapp.netlify.app/guide/overview.html
扫的是这里的菊花码。
手机是iqoo 8 pro 安卓13

**Comment by yang1206** [comment]
升级到 1.41会不会有背景色，目前小程序版本停留在 1.2，麻烦帮忙测试一下，目前手头没有安卓真机

**Comment by yang1206** [comment]
谢谢你的反馈，经过测试 1.4.1 安卓没有背景色了，由于微信那里审核的问题，小程序 demo 更新并不及时，下次可以自己跑个项目测试一下
