### ISSUE TITLE
Overlay、Popup组件小程序端不能正常关闭lockScroll

### ISSUE THREAD

**Issue by xiaohe0601** [nutui-uniapp/nutui-uniapp#103]
### nutui-uniapp 版本号

1.4.1

### 平台

weapp

### 重现链接

无

### 重现步骤

nut-overlay或nut-popup将lock-scroll设置为false

### 期望的结果是什么？

lock-scroll设置为false后，不再拦截弹窗内部的touchmove事件

### 实际的结果是什么？

lock-scroll设置为false后，弹窗内部的touchmove事件依然被拦截

### 其他补充信息

> @touchmove.stop.prevent="props.lockScroll ? toMoveHandle : ''"

只要加了 `.stop` 在小程序端就会被编译成 `catch:`，后面的值无论是什么都会拦截 `touchmove` 事件

**Comment by yang1206** [comment]
目前没有一个很好的方法控制lock-scroll，考虑后面的版本要不要弃用这个属性，用户自己使用 page-meta

**Comment by xiaohe0601** [comment]
微信小程序端必须是 `catchtouchmove="{{ lockScroll ? 'toMoveHandle' : '' }}"` 这种形式，才能有效控制是否 `catch`；

但是uniapp把 `@touchmove.stop.prevent="props.lockScroll ? toMoveHandle : ''"` 编译成了`catchtouchmove="{{o}}"`，`o`的值是一个函数来返回 `props.lockScroll ? toMoveHandle : ''`，这就导致了 `catchtouchmove` 接收到的值是一个函数，也就永远都会拦截 `touchmove` 事件了；

如果没有更好的办法，建议是废弃这个属性让用户自己处理，现在popup内部除了scroll-view以外其他元素都不能滑动，影响有点大了
