### ISSUE TITLE
Backtop组件不能完全返回到顶部

### ISSUE THREAD

**Issue by leecn-web** [nutui-uniapp/nutui-uniapp#104]
### nutui-uniapp 版本号

1.4.1

### 平台

weapp

### 重现链接

无

### 重现步骤

使用Backtop绑定click

### 期望的结果是什么？

回到顶部

### 实际的结果是什么？

离顶部剩一点点 好像是安全区的距离

**Comment by yang1206** [comment]
请提供复现工程，我这里测试没有问题
