### ISSUE TITLE
Cascader 级联选择 动态加载时，改变父级时，tab标题不会改变

### ISSUE THREAD

**Issue by 2509989976** [nutui-uniapp/nutui-uniapp#105]
### nutui-uniapp 版本号

1.2.3

### 平台

h5, weapp

### 重现链接

https://www.uniapp-nutui.tech/components/dentry/cascader.html

### 重现步骤

官网中的动态加载示例中也存在此问题。
重新步骤：
以官网中的  部分数据动态加载  案例为例
重现1：点击A0，到了二级时重新返回一级，再点击B0，此时tab中的标题依然是A0。
重现2：依次点击B0,B11。重新打开，重新选择 A0此时，tab标题不会改变，选中A11，此时tab标题变为正确的了。

### 期望的结果是什么？

无

### 实际的结果是什么？

无

**Comment by 2509989976** [comment]
刚测试了一下  基础用法  ，也是存在此问题。
重现：选择 浙江，返回，选择 福建，tab标题依然是浙江

**Comment by yang1206** [comment]
下一个版本将会修复，谢谢你的反馈！
