### ISSUE TITLE
Calendar 日历组件在微信小程序无法选择以前的日期。如果设置开始日期和结束日期无法默认定位的今天

### ISSUE THREAD

**Issue by xkfe** [nutui-uniapp/nutui-uniapp#108]
### nutui-uniapp 版本号

1.3.1

### 平台

weapp

### 重现链接

本仓库在微信小程序打开 直接查看Calendar 日历组件

### 重现步骤

本仓库在微信小程序打开 直接查看Calendar 日历组件

### 期望的结果是什么？

期望可以选择以前日期，并且默认定位到今天
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/129662190/6716637b-d3a2-4686-80ca-707abafa2740)

### 实际的结果是什么？

无法选中以前的日期

**Comment by yang1206** [comment]
小程序的行为是符合预期的，这里是h5有问题，你的要求属于新功能，请重新开一个 issue
