### ISSUE TITLE
[FR]: noticebar能不能支持数组内的object

### ISSUE THREAD

**Issue by travelCN** [nutui-uniapp/nutui-uniapp#109]
### 这个功能解决了什么问题？

目前只支持的文本，能不能支持object等格式。
能让click更有用。

### 你期望的组件设计是怎样的？

比如:list=list
```
const list = ref([
{
id:1,
content:'公告内容'
}
])
```

**Comment by yang1206** [comment]
下个版本将会支持`field-name`属性以供传递数组对象
