### ISSUE TITLE
[FR]: nut-switch可以期望添加一个before-change事件

### ISSUE THREAD

**Issue by xkfe** [nutui-uniapp/nutui-uniapp#110]
### 这个功能解决了什么问题？

点击后会调用接口，返回成功开启switch，失败则不执行后续操作。
现在定义change会导致陷入死循环。主动触发change -> 发送请求 -> 成功后刷新页面数据。结果change事件又触发了

### 你期望的组件设计是怎样的？

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/129662190/c1f4419a-e238-4861-bc0e-b15a3717c2aa)

**Comment by yang1206** [comment]
<img width="893" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/28709596/4d2ddb80-4502-4a18-92e7-55b68571d414">
<img width="544" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/28709596/068f0d2c-acca-4ff2-a5cc-ae9d46cdd2f8">

可以使用`model-value`属性加`update:model-value`代替 v-model应该可以满足你的需求，想要控制开关不应该在`change`事件中进行，后续我会更新文档
