### ISSUE TITLE
nutui-uniapp1.5.1 升级到nutui-uniapp 1.5.2后，支付宝小程序编译错误

### ISSUE THREAD

**Issue by blakelu** [nutui-uniapp/nutui-uniapp#117]
### nutui-uniapp 版本号

1.5.2

### 平台

alipay

### 重现链接

-

### 重现步骤

npm run dev:mp-alipay  
成功后，打开支付宝开发者工具打开项目出现以下问题
<img width="368" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/13463232/658cc0db-8709-456e-bedd-1ce304dadf21">
错误显示此语法不支持
<img width="952" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/13463232/8de50872-a383-4065-bba5-8b698bdeda68">

### 期望的结果是什么？

在支付宝小程序下正常运行

### 实际的结果是什么？

在支付宝小程序下正常运行

**Comment by blakelu** [comment]
<img width="1004" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/13463232/80e02f11-6447-495d-82e2-1a1624ab4c0c">
应该是这行编译后 多了一个“s”

**Comment by yang1206** [comment]
感谢反馈！
