### ISSUE TITLE
Calendar 日历组件 设置start-date参数只能限制到月份，start-date之前的日期仍是可以选中的

### ISSUE THREAD

**Issue by yangyuanftl** [nutui-uniapp/nutui-uniapp#124]
### nutui-uniapp 版本号

1.5.4

### 平台

h5, 其他小程序

### 重现链接

https://nutui-uniapp.netlify.app/components/dentry/calendar.html

### 重现步骤

`<nut-calendar
      :poppable="false"
      default-value="2023-11-15"
      start-date="2023-11-05"
      end-date="2023-11-20"
    />`
![Snipaste_2023-11-24_12-04-32](https://github.com/nutui-uniapp/nutui-uniapp/assets/25787942/8b7f4582-937a-468b-a2b2-8396d147dfbe)

### 期望的结果是什么？

仅可选中start-date和end-date之间的日期

### 实际的结果是什么？

start-date之前的日期仍是可选的

### 环境信息

H5和App都是如此，其他端不清楚

**Comment by yang1206** [comment]
<img width="328" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/28709596/abb7300a-ff44-4e4d-9afb-70bad258ef0a">

<img width="434" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/28709596/19bdae54-ff9f-426a-88b3-634c1508f8c4">


我这里测试没有问题啊，H5，能否提供一个复现实例

**Comment by yangyuanftl** [comment]
@yang1206 
是1.4.0有问题，我升级1.5.4之后没有重启项目。这会儿重启项目发现是正确的
