### ISSUE TITLE
[FR]: RadioGroup 能否增加只读属性

### ISSUE THREAD

**Issue by travelCN** [nutui-uniapp/nutui-uniapp#126]
### 这个功能解决了什么问题？

虽然有禁用，是否可以跟input一样 有只读属性？

### 你期望的组件设计是怎样的？

虽然有禁用，是否可以跟input一样 有只读属性？

**Comment by yang1206** [comment]
没有足够的使用场景，如果你不想要改变值，不使用 v-model，改用model-value属性即可
