### ISSUE TITLE
calendar 微信小程序里 没有 btn slots 却仍然有占位行

### ISSUE THREAD

**Issue by cnhuye** [nutui-uniapp/nutui-uniapp#131]
### nutui-uniapp 版本号

1.5.6

### 平台

weapp

### 重现链接

https://nutui-uniapp.netlify.app/components/dentry/calendar.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%A6%81%E7%94%A8%E6%97%A5%E6%9C%9F

### 重现步骤

从官方示例中复制的代码 ** 自定义禁用日期 ** 这个，在小程序开发工具中可以看到问题。
图片里红框处的问题。
![WX20231130-211853@2x](https://github.com/nutui-uniapp/nutui-uniapp/assets/486552/10e7b809-af3b-46a0-bbdf-3d15517f971e)

代码里并没有使用 btn slots, 在 H5中显示正常，但在微信小程序里会有一行空白。

### 期望的结果是什么？

没有 .nut-calendar__header-slot 这一行

### 实际的结果是什么？

没有使用  btn slots 时 在微信小程序里仍然会有  .nut-calendar__header-slot 的空白行

### 环境信息

  System:
    OS: macOS 13.4.1
    CPU: (8) x64 Apple M2
    Memory: 15.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v18.14.2/bin/npm
    pnpm: 7.30.0 - ~/.nvm/versions/node/v18.14.2/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.105
    Safari: 16.5.2
  npmPackages:
    nutui-uniapp: ^1.5.6 => 1.5.6 

### 其他补充信息

vue 3

**Comment by yang1206** [comment]
这是因为 uniapp 的 slot 机制有问题，嵌套组件 slot会默认显示，没办法使用 vue 的 useSlots进行判断，下个版本会增加属性让用户控制是否使用对应的 slot，可以参考calendar的 footer 插槽的使用
