### ISSUE TITLE
[FR]: 期望支持全局的 Dark 模式

### ISSUE THREAD

**Issue by normal-coder** [nutui-uniapp/nutui-uniapp#133]
### 这个功能解决了什么问题？

  当前的 Dark 模式是基于组件的。但对页面级或全局级别的 Dark 模式并未支持。

### 你期望的组件设计是怎样的？

在 `pages.json` 中支持变量，用于统一管理 Dark 模式

```json
    "globalStyle": {
        "navigationBarTitleText": "xxxxx",
        "backgroundColor": "#F8F8F8",
        "navigationBarBackgroundColor": "@navBgColor",
        "navigationBarTextStyle": "@navTxtStyle"
    },
```

**Comment by normal-coder** [comment]
目前看已发布的微信小程序 Demo 也没有对页面背景色。Tab 主题色做 Dark 的切换。从网站 Demo 看 Example 比较少。没想明白是怎么实现 😂 建议可以考虑做个 Demo（或许我应该更多的学习一下源码，但还是提提改进 Example 的建议），感谢

**Comment by normal-coder** [comment]
> 这与组件库无关，具体实现只与你项目的设计有关，组件库本身支持你说的效果，具体请查看example目录的实现

目前看已发布的微信小程序 Demo 也没有对页面背景色。Tab 主题色做 Dark 的切换。从网站 Demo 看 Example 比较少。没想明白是怎么实现 😂 建议可以考虑做个 Demo（或许我应该更多的学习一下源码，但还是提提改进 Example 的建议），感谢 @yang1206

**Comment by yang1206** [comment]
> > 这与组件库无关，具体实现只与你项目的设计有关，组件库本身支持你说的效果，具体请查看example目录的实现
> 
> 
> 
> 目前看已发布的微信小程序 Demo 也没有对页面背景色。主题色做 Dark 的切换。从网站 Demo 看 Example 比较少。没想明白是怎么实现 😂 建议可以考虑做个 Demo（或许我应该更多的学习一下源码，但还是提提改进 Example 的建议），感谢 @yang1206 

小程序不支持主动切换主题，只能根据系统主题自动切换，如果你想实现主动切换，只能使用css var等方式
