### ISSUE TITLE
1.5.8版本的Popup 搭配 Picker, 在APP端会v-model:visible无法控制（页面内默认弹出状态, 且无法关闭）。

### ISSUE THREAD

**Issue by yangyuanftl** [nutui-uniapp/nutui-uniapp#142]
### nutui-uniapp 版本号

1.5.8

### 平台

其他小程序

### 重现链接

https://nutui-uniapp.netlify.app/components/dentry/picker.html

### 重现步骤

今天删除node_modules文件夹，重新pnpm i 安装所有依赖后，测试时发现此问题，切换回旧版本就正常了，猜测是此版本有问题。

APP端，最新版本（1.5.8）Popup 搭配 Picker，
切换旧版本就正常了

### 期望的结果是什么？

修复

### 实际的结果是什么？

未修复

**Comment by cnhuye** [comment]
遇到相同问题， 1.5.8/1.5.9  uniapp 开发的 IOS APP，iPhone模拟器里 弹窗无法控制，默认都会打开，并且关闭不了。H5上没有问题。

**Comment by cnhuye** [comment]
经测试，这个BUG在 1.5.8/1.5.9 中出现， 1.5.7 及之前版本没有。

**Comment by NicCraver** [comment]
我加了个if （笑哭）就是动画没有了

**Comment by yang1206** [comment]
请提供一个复现的 demo

**Comment by cnhuye** [comment]
[nut-test.zip](https://github.com/nutui-uniapp/nutui-uniapp/files/13769136/nut-test.zip)

做了一个复现demo.

过程如下:
```
npx degit dcloudio/uni-preset-vue#vite nut-test
yarn add nutui-uniapp sass
```
按官方文档 修改了 `vite.config.js`, `App.vue`, `index.vue` 几个文件。
使用 iPhone 模拟器运行APP就能看到问题。

**Comment by yang1206** [comment]
谢谢，请尝试升级新版看看
