### ISSUE TITLE
sku组件文档的预览无法加载，导致页面崩溃

### ISSUE THREAD

**Issue by 74jian** [nutui-uniapp/nutui-uniapp#147]
### nutui-uniapp 版本号

1.5.9

### 平台

其他小程序

### 重现链接

https://www.uniapp-nutui.tech/components/business/sku.html

### 重现步骤

打开文档链接

### 期望的结果是什么？

正常浏览

### 实际的结果是什么？

预览页面无法加载，导致文档页面崩溃

**Comment by yang1206** [comment]
感谢反馈

**Comment by yang1206** [comment]
现在应该已经正常了
