### ISSUE TITLE
input 有没有value的颜色问题？

### ISSUE THREAD

**Issue by travelCN** [nutui-uniapp/nutui-uniapp#148]
### nutui-uniapp 版本号

1.5.9

### 平台

weapp

### 重现链接

无

### 重现步骤

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/15223877/de8ce2f5-0de6-4a0b-918e-c61617544b2e)
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/15223877/c3677e76-eb39-4fc8-bd75-69be39db15b4)
这个值的颜色是灰色的。。有没有遇到这种情况的。

### 期望的结果是什么？

正常黑色

### 实际的结果是什么？

灰色

**Comment by NicCraver** [comment]
我也遇到了
<img width="435" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/36131101/245cdab7-a93e-410b-928f-ac669063a9be">

**Comment by NicCraver** [comment]
加了各种css都无效

**Comment by NicCraver** [comment]
.input-text {
    color: #000 !important;
  }
  这样可以了 @travelCN

**Comment by travelCN** [comment]
我是每个都加了 custom-style。 @NicCraver 
网站的例子上倒是没有这情况。
