### ISSUE TITLE
安卓APP中，nut-navbars顶部安全区域无效

### ISSUE THREAD

**Issue by MrChildrenHY** [nutui-uniapp/nutui-uniapp#150]
### nutui-uniapp 版本号

1.5.9

### 平台

其他小程序

### 重现链接

无

### 重现步骤

    <nut-navbar
      title="我是标题"
      :safe-area-inset-top="true"
      :placeholder="true"
      :fixed="true"
    />

 APP上效果是顶到屏幕最上方了，没有留出状态栏的安全高度，

### 期望的结果是什么？

自动空出状态栏

### 实际的结果是什么？

状态栏被占用了

**Comment by RJQingHuan** [comment]
+1
