### ISSUE TITLE
Calendar 日历组件微信小程序bug，第一次打开空白，滚动后才显示，设置起始和结束日期后，打开日历滚动位置不在默认日期的所在月份

### ISSUE THREAD

**Issue by LeeLulin** [nutui-uniapp/nutui-uniapp#152]
### nutui-uniapp 版本号

1.5.9

### 平台

weapp

### 重现链接

https://nutui-uniapp.netlify.app/components/dentry/calendar.html

### 重现步骤

设置日历组件的default-value为['2024-01-01', '2024-01-03']，start-date="2022-01-01"，end-date="2024-01-04"

    <nut-calendar
      v-model:visible="state.showDate"
      type="range"
      title="出库时间"
      :default-value="state.defaultDate"
      start-date="2022-01-01"
      end-date="2024-01-04"
      @choose="dateChoose"
      :is-auto-back-fill="true"
    ></nut-calendar>

第一次打开页面空白：
<img width="387" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/27431274/a67a2171-a9cd-4d1c-9299-1bb0e84ff457">

滚动后页面显示正常，但是页面显示的默认月份不正确：
<img width="390" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/27431274/e6777ec2-3e67-455b-b8c4-9b02bcd76568">

### 期望的结果是什么？

第一次打开不显示空白，日历可以滚动到当前默认日期所在的月份

### 实际的结果是什么？

第一次打开空白，滚动后才显示，设置起始和结束日期后，打开日历滚动位置不在默认日期的所在月份

### 环境信息

  System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.22 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    pnpm: 7.21.0 - /usr/local/bin/pnpm
  Browsers:
    Edge: 120.0.2210.91
    Safari: 17.1
  npmPackages:
    nutui-uniapp: ^1.5.9 => 1.5.9

**Comment by LeeLulin** [comment]
示例代码：https://github.com/LeeLulin/nutui-uniapp-demo

**Comment by yang1206** [comment]
> 示例代码：https://github.com/LeeLulin/nutui-uniapp-demo @yang1206 

谢谢，有时间我会看

**Comment by yang1206** [comment]
暂时可以在弹出日历的同时调用
`  calendarRef.value.scrollToDate('2024-01-01')
`
