### ISSUE TITLE
H5环境下使用nut-popup，无弹出效果

### ISSUE THREAD

**Issue by cqzhong** [nutui-uniapp/nutui-uniapp#158]
### nutui-uniapp 版本号

1.6.3

### 平台

h5

### 重现链接

wu

### 重现步骤

 <nut-popup :custom-style="{ padding: '30px 50px' }" v-model:visible="showBasic">正文</nut-popup>

### 期望的结果是什么？

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/10128830/eea6f2b7-4409-4d94-8e27-621e1715cfc7)

### 实际的结果是什么？

更新为1.5.9之后的版本，就变成了以下效果
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/10128830/ed76cb69-e093-47d7-9201-a288c7046121)

### 环境信息

  System:
    OS: macOS 14.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 473.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.13.2 - ~/node_modules/.bin/npm
    pnpm: 8.6.5 - /usr/local/bin/pnpm
    Watchman: 2023.06.26.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.2.1

**Comment by cqzhong** [comment]
仓库地址：https://github.com/cqzhong/test-nutui-uniapp

##1.5.9版本正常
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/10128830/b6156dc5-0a61-4652-b881-822cf5b6f14b)

##1.5.9版本以后
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/10128830/afb3f8a6-d88f-4059-b207-a0c770f55150)

**Comment by yang1206** [comment]
去除你pages.json中easycom导入即可
