### ISSUE TITLE
DatePicker 日期选择器组件有错别字 

### ISSUE THREAD

**Issue by zygDemo** [nutui-uniapp/nutui-uniapp#159]
### nutui-uniapp 版本号

v1.6.3

### 平台

h5

### 重现链接

https://nutui-uniapp.netlify.app/components/dentry/datepicker.html

### 重现步骤

![微信图片_20240109102355](https://github.com/nutui-uniapp/nutui-uniapp/assets/45715263/b3fda624-cfce-4643-8b94-da05eb2e295e)

### 期望的结果是什么？

确实-->确定

### 实际的结果是什么？

确实

**Comment by yang1206** [comment]
这里是配置了自定义国际化文字，不是错别字
