### ISSUE TITLE
亮色模式下，input框的颜色不对

### ISSUE THREAD

**Issue by djkloop** [nutui-uniapp/nutui-uniapp#165]
### nutui-uniapp 版本号

1.6.3

### 平台

weapp

### 重现链接

https://nutui-uniapp.netlify.app/components/dentry/input.html

### 重现步骤

官网打开就能复现

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/21050914/53b944a4-4bae-4c01-b57d-1e024eacc1ff)

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/21050914/79efea55-1abe-46c5-8d96-3e3b1dcd302b)

### 期望的结果是什么？

正确显示

### 实际的结果是什么？

没有正确显示

### 环境信息

```sh
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 11.63 GB / 31.78 GB
  Binaries:
    Node: 18.17.0 - D:\soft\nvm-node\node.EXE
    Yarn: 1.17.0 - D:\soft\nvm-node\yarn.CMD
    npm: 9.6.7 - D:\soft\nvm-node\npm.CMD
    pnpm: 8.6.9 - D:\soft\nvm-node\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    nutui-uniapp: ^1.5.9 => 1.5.9

```

**Comment by yang1206** [comment]
<img width="408" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/28709596/71c3ec65-1042-460f-aff5-30b125cd048c">
没有复现

**Comment by minxiang51574** [comment]
https://github.com/nutui-uniapp/nutui-uniapp/pull/166
已提交pr

**Comment by djkloop** [comment]
@yang1206 是浏览器深色模式下，然后把官网的亮色模式打开就出现这个bug了，感觉还是给个默认颜色比较好，依赖设备的颜色有时候不对，我在小程序里面有时候颜色也不对，input的亮色模式颜色偏暗...
