### ISSUE TITLE
在现有微信小程序项目按照快速上手流程导入，引入button报错

### ISSUE THREAD

**Issue by 601544679** [nutui-uniapp/nutui-uniapp#169]
### nutui-uniapp 版本号

1.6.4

### 平台

weapp

### 重现链接

https://github.com/nutui-uniapp/nutui-uniapp/issues/new?assignees=&labels=&projects=&template=bug-report.yml

### 重现步骤

**1.pnpm add nutui-uniapp引入组件**

**2.配置pages.json**
 // 组件自动导入
  "easycom": {
    "autoscan": true,
    "custom": {
      // uni-ui 规则如下配置
      "^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue",
      "^nut-(.*)?-(.*)": "nutui-uniapp/components/$1$2/$1$2.vue",
      "^nut-(.*)": "nutui-uniapp/components/$1/$1.vue",
      "^uv-(.*)": "@climblee/uv-ui/components/uv-$1/uv-$1.vue",
      "^(?!z-paging-refresh|z-paging-load-more)z-paging(.*)": "z-paging/components/z-paging$1/z-paging$1.vue"
    }
  },

**3.配置vite.config.ts**
import { defineConfig, loadEnv } from "vite"
import Components from "@uni-helper/vite-plugin-uni-components"
import { NutResolver } from "nutui-uniapp"
import uni from "@dcloudio/vite-plugin-uni"
const { resolve } = require("path")

// https://vitejs.dev/config/
export default defineConfig(({ mode, command }) => {
  const env = loadEnv(mode, process.cwd())
  // console.log("env", env)
  return {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@import "nutui-uniapp/styles/variables.scss";',
        },
      },
    },
    plugins: [
      Components({
        resolvers: [NutResolver()],
      }),
      uni(),
    ],
    base: env.VITE_APP_BASE_API,
    resolve: {
      alias: {
        "@": resolve(__dirname, "./src"), // 路径别名
      },
      extensions: [".vue", ".js", ".json", ".ts"], // 使用路径别名时想要省略的后缀名，可以自己 增减
    },
  }
})

**4.根目录配置 .npmrc**
// .npmrc
public-hoist-pattern[]=@vue*
// or
// shamefully-hoist = true

**5.App.vue引入样式**
<style lang="scss">
@import "nutui-uniapp/styles/index.scss";

### 期望的结果是什么？

成功引入组件

### 实际的结果是什么？

报错内容
VM839:11 页面【node-modules/nutui-uniapp/components/button/button]错误:
 ReferenceError: buttonProps is not defined
    at button.js? [sm]:19
    at WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1
    at d.runWith (WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1)
    at V (WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1)
    at <anonymous>:8:5
    at evaluateRes (index.js:1)
    at index.js:1
    at Object.invoke (index.js:1)
    at r (index.js:1)
    at Object.invoke (WAServiceMainContext.js?t=wechat&s=1705563939231&v=3.0.0:1)(env: macOS,mp,1.06.2401020; lib: 3.0.0)
(anonymous) @ VM839:11
ReferenceError: buttonProps is not defined
    at button.js? [sm]:19
    at WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1
    at d.runWith (WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1)
    at V (WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1)
    at <anonymous>:8:5
    at evaluateRes (index.js:1)
    at index.js:1
    at Object.invoke (index.js:1)
    at r (index.js:1)
    at Object.invoke (WAServiceMainContext.js?t=wechat&s=1705563939231&v=3.0.0:1)(env: macOS,mp,1.06.2401020; lib: 3.0.0)
VM840:11 页面【node-modules/nutui-uniapp/components/icon/icon]错误:
 ReferenceError: iconProps is not defined
    at icon.js? [sm]:15
    at WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1
    at d.runWith (WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1)
    at V (WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1)
    at <anonymous>:8:5
    at evaluateRes (index.js:1)
    at index.js:1
    at Object.invoke (index.js:1)
    at r (index.js:1)
    at Object.invoke (WAServiceMainContext.js?t=wechat&s=1705563939231&v=3.0.0:1)(env: macOS,mp,1.06.2401020; lib: 3.0.0)
(anonymous) @ VM840:11
ReferenceError: iconProps is not defined
    at icon.js? [sm]:15
    at WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1
    at d.runWith (WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1)
    at V (WASubContext.js?t=wechat&s=1705563939231&v=3.0.0:1)
    at <anonymous>:8:5
    at evaluateRes (index.js:1)
    at index.js:1
    at Object.invoke (index.js:1)
    at r (index.js:1)
    at Object.invoke (WAServiceMainContext.js?t=wechat&s=1705563939231&v=3.0.0:1)(env: macOS,mp,1.06.2401020; lib: 3.0.0)
Component is not found in path "node-modules/nutui-uniapp/components/button/button" (using by "pages/my/productInventory/productInventory")(env: macOS,mp,1.06.2401020; lib: 3.0.0)

### 环境信息

System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 106.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.14.0 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2.1
  npmPackages:
    nutui-uniapp: ^1.6.4 => 1.6.4 

### 其他补充信息

 "dependencies": {
    "@climblee/uv-ui": "^1.1.19",
    "@dcloudio/uni-app": "3.0.0-3090920231225001",
    "@dcloudio/uni-app-plus": "3.0.0-3090920231225001",
    "@dcloudio/uni-components": "3.0.0-3090920231225001",
    "@dcloudio/uni-h5": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-alipay": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-baidu": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-jd": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-lark": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-qq": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-toutiao": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-weixin": "3.0.0-3090920231225001",
    "@dcloudio/uni-quickapp-webview": "3.0.0-3090920231225001",
    "@dcloudio/uni-ui": "^1.5.0",
    "nutui-uniapp": "^1.6.4",
    "pinia": "2.0.36",
    "pinia-plugin-persistedstate": "^3.2.1",
    "sass": "^1.69.7",
    "vue": "3.2.47",
    "vue-i18n": "^9.9.0",
    "z-paging": "^2.7.4"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.4.7",
    "@dcloudio/uni-automator": "3.0.0-3090920231225001",
    "@dcloudio/uni-cli-shared": "3.0.0-3090920231225001",
    "@dcloudio/uni-stacktracey": "3.0.0-3090920231225001",
    "@dcloudio/vite-plugin-uni": "3.0.0-3090920231225001",
    "@uni-helper/uni-ui-types": "^0.5.11",
    "@uni-helper/vite-plugin-uni-components": "^0.0.8",
    "@vue/tsconfig": "^0.1.3",
    "typescript": "^4.9.5",
    "vite": "^4.5.1",
    "vue-tsc": "^1.8.27"
  }

**Comment by 601544679** [comment]
https://gitee.com/djx601544679_admin/nutui-uniapp-test.git
简单的测试用例，依然报错
Component is not found in path "node-modules/nutui-uniapp/components/button/button" (using by "pages/index/index")(env: macOS,mp,1.06.2401020; lib: 3.3.3)

**Comment by xiaohe0601** [comment]
@601544679 提供的最小重现实例未复现出问题，可以尝试更新微信开发者工具~

**Comment by 601544679** [comment]
可能是m1或者macOS Sonoma14.2.1 (23C71)的问题，win11上能展示组件，而mac不行

**Comment by xiaohe0601** [comment]
> 可能是m1或者macOS Sonoma14.2.1 (23C71)的问题，win11上能展示组件，而mac不行

这个环境下也未能复现出问题

可以检查一下 `dist/dev/mp-weixin/node-modules/nutui-uniapp/components/button/button.js` 文件是否存在，以及 `dist/dev/mp-weixin/pages/index/index.json` 中 `usingComponents` 字段中 `nut-button` 是否正确

**Comment by yang1206** [comment]
easycom和组件自动导入二选一而不是同时使用试试看

**Comment by thunderfalco** [comment]
这个bug依然存在，不仅仅是button存在这个问题，icon组件也存在这个问题

**Comment by zhuchentong** [comment]
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/4535888/542aaf18-cca5-441b-8092-c84723b55dde)

**Comment by xiaohe0601** [comment]
@zhuchentong 请检查nodejs及uniapp版本

**Comment by xiaohe0601** [comment]
@zhuchentong 经排查，不是组件库的问题，建议删除node_modules及lock文件，重新安装依赖，应该是项目中某个依赖内部的依赖版本未锁定导致的问题，具体是哪个依赖还需要再排查

**Comment by xiaohe0601** [comment]
> ![image](https://private-user-images.githubusercontent.com/4535888/335920213-542aaf18-cca5-441b-8092-c84723b55dde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzUzNDQsIm5iZiI6MTcxNzU3NTA0NCwicGF0aCI6Ii80NTM1ODg4LzMzNTkyMDIxMy01NDJhYWYxOC1jY2E1LTQ0MWItODA5Mi1jODQ3MjNiNTVkZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMDgxMDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjM5NGE1OTZkZWJhNDE1OGVlZGJhMmIxZjEzZGUzMWJmM2NiYzQ3ZjUyZWNiOTFlMWIyMWM2ZjkzNTdmM2NkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5uyh7z5k_YsUBZOJnDH4GhJweI4MqIdVCIfvze_yDF0)

关联 #341
