### ISSUE TITLE
[FR]: 主题色缺少其他颜色定义

### ISSUE THREAD

**Issue by de1ck** [nutui-uniapp/nutui-uniapp#171]
### 这个功能解决了什么问题？

目前只有$primary-color 主色调的变量可以覆盖，success, warning, danger, error, info 等颜色没有单独抽取变量，需要每个组件一一覆盖

### 你期望的组件设计是怎样的？

需要跟Element-Plus 抽取可配置的各个色的变量配置[Element-Plus](https://element-plus.org/en-US/guide/theming.html)

**Comment by de1ck** [comment]
no planed

**Comment by zhaoyunyes** [comment]
我也发现了这个问题了。目前手动覆盖的方案极容易漏掉或者覆盖错，期望官方尽快提取相关css变量出来
