### ISSUE TITLE
button按钮设置为disabled后，getphonenumber方法仍然可以触发

### ISSUE THREAD

**Issue by scout927** [nutui-uniapp/nutui-uniapp#173]
### nutui-uniapp 版本号

1.6.5

### 平台

weapp

### 重现链接

无

### 重现步骤

nut-button组件设置为disabled后，open-type="getPhoneNumber"，@getphonenumber还是可以触发获取手机号

### 期望的结果是什么？

设置为disabled后，@getphonenumber应该不会触发

### 实际的结果是什么？

设置为disabled后，getphonenumber方法还是弹出了获取手机号弹框

**Comment by yang1206** [comment]
已修复
