### ISSUE TITLE
怎么可以清空掉button里面的border ?

### ISSUE THREAD

**Issue by Yer11214** [nutui-uniapp/nutui-uniapp#177]
### nutui-uniapp 版本号

1.6.6

### 平台

h5, weapp

### 重现链接

本地使用nut-button

## 样式是这样的
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/39794167/89a20b7e-16bc-4510-b597-aa8cdcfbf8db)
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/39794167/1b7e81f8-6bbd-46a8-81fa-ad23932837bc)
## 代码是这样的 小程序平台
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/39794167/18ae3e06-b1b4-408e-9929-fb42ea95464f)

### 期望的结果是什么？

可以清空border 

### 实际的结果是什么？

不能清空

### 环境信息

  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 3.11 GB / 31.78 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.22621.1

**Comment by xiaohe0601** [comment]
```css
.custom-button {
  --nut-button-border-width: 0;
}
```

**Comment by Yer11214** [comment]
我试了一下不行的 = = 微信小程序这里
### 页面
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/39794167/565aaa87-769f-4399-9c84-cbd6153e94d2)

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/39794167/ff85c7e9-990c-4702-b6cb-983fd216b0b5)
### 代码
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/39794167/3912bf17-dbbb-4484-91a5-af2f024a2ea6)

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/39794167/dc7ff613-78f3-4590-bb1a-b4c85addbddf)

**Comment by yang1206** [comment]
新建一个scss文件
