### ISSUE TITLE
dialog组件1.5.9版本以后APP显示异常

### ISSUE THREAD

**Issue by madehua** [nutui-uniapp/nutui-uniapp#192]
### nutui-uniapp 版本号

1.6.9

### 平台

weapp

### 重现链接

https://github.com/madehua/nutui-datepicker-demo

### 重现步骤

1、打开页面
http://localhost:5173/#/pages/nutui/dialog/dialog
2、点击基础弹框
![微信图片_20240222191303](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/ed06055e-40e7-4d8d-99ef-a1b822607ceb)
3、代码片段为官方代码

### 期望的结果是什么？

弹窗正常
<img width="441" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/6941e9eb-b11a-48cc-8782-00357202fdb4">

### 实际的结果是什么？

弹窗显示错误
![微信图片_20240222191303](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/2c7aa9b8-39f1-4f85-8a55-d182c930e8cd)

### 环境信息

System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 3.01 GB / 15.73 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (113.0.1774.42)
    Internet Explorer: 11.0.22621.1

**Comment by yang1206** [comment]
感谢反馈

**Comment by xiaohe0601** [comment]
@yang1206 我看了下，估计是uniapp的bug，在app端对`多根节点`组件支持的不太行，我调整了一下 #194
