### ISSUE TITLE
menu菜单组件几个问题

### ISSUE THREAD

**Issue by madehua** [nutui-uniapp/nutui-uniapp#196]
### nutui-uniapp 版本号

1.7.0

### 平台

h5, weapp

### 重现链接

https://github.com/madehua/nutui-datepicker-demo

### 重现步骤

1、运行项目首页，点击Menu菜单示例
<img width="319" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/34b70af8-605a-4919-bf78-cb21d76f2ded">
2、代码片段为官方示例
<img width="743" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/116c49d2-8a2f-4bd9-8059-b4203312b19b">

### 期望的结果是什么？

1、h5端有uniapp有标题时跟随菜单下显示。
<img width="207" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/bc8cd4a5-e108-4d26-9106-7852957a5b31">

2、app端打开页面后，有一个整屏透明遮罩层，期望默认去遮罩层。
注：在nut-menu-item 设置custom-style="display:none" 可正常使用。

3、close事件可以正常触发，且只触发一次。

### 实际的结果是什么？

1、h5端有uniapp标题时显示位置不对，点击下拉按钮，覆盖了菜单本身。
<img width="316" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/1e4c05bf-7429-4f2e-ba3d-a27537a80814">
<img width="328" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/891347c3-9bba-4018-a27b-d9e266a7e247">

2、app端打开页面后，有一个整屏透明遮罩层，导致无法点击假死状态
![700a4b87d3cbd3c6e2c998319e3b43f](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/735f413d-8a8d-42a3-ab6f-8dec32403f15)
注：在nut-menu-item 设置custom-style="display:none" 可正常使用。

3、close事件在微信端不触发，在h5及app端触发两次。
app端表现
<img width="551" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/3adf87b4-1dd3-4a9d-8f66-d4793bdfd5f3">
h5端表现
<img width="888" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/507fedce-9b9b-4216-b5a3-46db560b94e0">
微信端表现
<img width="532" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/cf4ab511-4b4f-4b2e-9795-fdf05c528103">

### 环境信息

System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 1.35 GB / 15.73 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (113.0.1774.42)
    Internet Explorer: 11.0.22621.1

### 其他补充信息

昨天反馈了2个问题，感谢处理问题的速度。点赞！

**Comment by yang1206** [comment]
> 问题2是app端 `v-show` 优先级不足导致的，跟 #149 一样的问题，要完全兼容app端，看是不是需要把所有 `v-show` 都换掉？ @yang1206

可以，问题 1 似乎是因为 h5获取的节点坐标不包含导航栏高度

**Comment by yang1206** [comment]
我会提一个 pr 解决这些问题

**Comment by yang1206** [comment]
第三个问题涉及多个组件，后续我会再开一个 pr 单独修复
