### ISSUE TITLE
form.validate在prop是数组时required无效

### ISSUE THREAD

**Issue by RJQingHuan** [nutui-uniapp/nutui-uniapp#200]
### nutui-uniapp 版本号

1.6.9

### 平台

h5

### 重现链接

https://www.xxx.com

### 重现步骤

建立form,prop值为数组,并且添加required验证

### 期望的结果是什么？

prop为数组类型并且数组为空时required校验失败

### 实际的结果是什么？

prop为数组类型并且数组为空时required校验成功

**Comment by xiaohe0601** [comment]
thx!
