### ISSUE TITLE
[FR]: Cascader组件options层级不一致时选择数量必须和最大层级一致

### ISSUE THREAD

**Issue by RJQingHuan** [nutui-uniapp/nutui-uniapp#206]
### 这个功能解决了什么问题？

```javascript
const options =[
  {
    id: '1',
    name: '浙江',
    children: [
      {
        id: '2',
        name: '杭州',
        disabled: true,
        children: [
          { id: '3', name: '西湖区' },
          { id: '4', name: '余杭区' },
        ],
      },
    ],
  },
  {
    id: '9',
    name: '福建',
    children: [
      {
        id: '10',
        name: '福州',
        children: [
        ],
      },
    ],
  },
]
``` 

上面的数据作为options的最大层级为3,至少应该选择3个城市,当前组件选择`福建/福州`也会选择成功

### 你期望的组件设计是怎样的？

如所选结果数量未达到最大层级时不改变已有数据

**Comment by xiaohe0601** [comment]
可以考虑加个参数控制最小选择层级

**Comment by yang1206** [comment]
个人认为这并不是一个合理的需求，因为大多数情况下每一个选项的层级并不一致，这个更改属于BREAKING CHANGE了，我觉得我们还需要再讨论一下

**Comment by RJQingHuan** [comment]
添加参数控制最小层级，默认为1如何？这样不属于BREAKING CHANGE

**Comment by RJQingHuan** [comment]
我思考了一下，添加一个单独的参数确实会增加心智负担。按理说可以通过主动设置`leaf`为`false`来控制是否时叶子节点,如果`leaf`等于`false`时就算`children`没有数据,也应该不触发数据更改.

但是现在就算主动设置`leaf=false`, `children`没有数据时也会改变数据,我认为这是一个小BUG

你们觉得如何?如果可以,我可以单独提交一个PR来修复这个问题,同时完善一下文档说明

**Comment by yang1206** [comment]
> 我思考了一下，添加一个单独的参数确实会增加心智负担。按理说可以通过主动设置`leaf`为`false`来控制是否时叶子节点,如果`leaf`等于`false`时就算`children`没有数据,也应该不触发数据更改.
> 
> 
> 
> 但是现在就算主动设置`leaf=false`, `children`没有数据时也会改变数据,我认为这是一个小BUG
> 
> 
> 
> 你们觉得如何?如果可以,我可以单独提交一个PR来修复这个问题,同时完善一下文档说明

我觉得可以
