### ISSUE TITLE
Uploader 上传组件，APP端右上角X按钮无响应。

### ISSUE THREAD

**Issue by madehua** [nutui-uniapp/nutui-uniapp#207]
### nutui-uniapp 版本号

1.7.0

### 平台

weapp

### 重现链接

https://github.com/madehua/nutui-datepicker-demo

### 重现步骤

1、打开应用首页
2、点击uploader上传按钮
3、点击右上角X，无反应。
![1709177488250](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/9930f0be-b636-42f5-900d-c01c587aa6ea)

### 期望的结果是什么？

delete事件正常触发

### 实际的结果是什么？

app端点击关闭无反应，delete事件不触发.
提示 TypeError: props.beforeDelete is not a function
<img width="610" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/1c5b9a2b-ca02-44c8-8bc9-c08b19581bae">

**Comment by shuTwT** [comment]
没在仓库中找到你的代码

**Comment by madehua** [comment]
> 没在仓库中找到你的代码

不好意思，刚才没有推送成功。

https://github.com/madehua/nutui-datepicker-demo/tree/main/src/pages/nutui/uploader
