### ISSUE TITLE
Avatar  h5*app端size不生效，h5、app、微信 shape不生效

### ISSUE THREAD

**Issue by madehua** [nutui-uniapp/nutui-uniapp#211]
### nutui-uniapp 版本号

1.7.1

### 平台

h5, weapp

### 重现链接

https://github.com/madehua/nutui-datepicker-demo/blob/main/src/pages/nutui/avatar/avatar.vue

### 重现步骤

https://github.com/madehua/nutui-datepicker-demo/blob/main/src/pages/nutui/avatar/avatar.vue

<img width="500" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/53757022-00b3-46ea-8847-b51dcd3a5c39">

### 期望的结果是什么？

size  shape 属性正常生效。

### 实际的结果是什么？

h5端，大小不受控
<img width="316" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/1d7414f2-54a2-43cb-ba94-92ea7b512692">
h5、微信、app，圆形头像不生效
<img width="227" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/b6db4a4d-5f53-466c-ae12-1e50ada8b89c">

**Comment by xiaohe0601** [comment]
请使用 `image` 组件代替 `img` 标签

```html
<nut-avatar size="normal" shape="round">
  <image src="https://t7.baidu.com/it/u=1595072465,3644073269&fm=193&f=GIF" />
</nut-avatar>
```

**Comment by madehua** [comment]
<img width="200" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/303227bc-93e6-4aff-897c-1e222ae54672">
![0905679f2cf12b4e736462b4fdd46d1](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/212844da-a168-47ab-bd04-4c65fd7ef17a)
替换以后，APP端大小还是不对哦~

头像还是方的，文档示例的图片本身是png圆形图片。

**Comment by yang1206** [comment]
你需要自行给图片样式进行限制

**Comment by xiaohe0601** [comment]
经测试，app端的表现异常大概率为 `uni-app` 内部缺陷，组件内部无法为 `image` 添加样式，若需兼容app端，请手动为子元素添加样式，例如：

```vue
<nut-avatar size="normal" shape="round">
  <image :style="{ width: '100%', height: '100%' }" src="......"></image>
</nut-avatar>

<nut-avatar size="normal" shape="round">
  <nut-icon :style="{ verticalAlign: 'middle' }" name="......" />
</nut-avatar>

<!-- style仅为示例，实际编码中使用style、class均可 -->
```
