### ISSUE TITLE
[FR]: 类型建议

### ISSUE THREAD

**Issue by shuTwT** [nutui-uniapp/nutui-uniapp#226]
### 这个功能解决了什么问题？

如图所示，props的默认值设置为了null，但是type设置的是`Function`
<img width="389" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/95295076/9e74591a-056b-4f70-bfd8-d77cfa6c9cfa">
这就导致了
<img width="777" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/95295076/1818e703-4d31-4bbf-8c7f-aba2c22dbbf7">
在使用时是这样子的
<img width="426" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/95295076/ccd9e71b-faad-427d-8ce9-f8274226c917">
props在未赋默认值是为undefined
在不设置`props.beforeUpload`时也可实现功能
如果将默认值设为空函数`()=>{}`
在执行`props.beforeUpload()`时由于是空函数，也不受影响

### 你期望的组件设计是怎样的？

规范类型，消除警告

**Comment by xiaohe0601** [comment]
#208 已经处理了这个问题咯，等待下个版本发布即可~

**Comment by xiaohe0601** [comment]
目前把所有`Function`类型的属性的默认都设置为了`null`，因为在app端`Function`类型的属性默认值必须写成下面这样才能生效
```typescript
{
  type: Function,
  default() {
    return () => {
      return true
    }
  }
}
```
