### ISSUE TITLE
Input customStyle

### ISSUE THREAD

**Issue by de1ck** [nutui-uniapp/nutui-uniapp#230]
### nutui-uniapp 版本号

v1.7.2

### 平台

weapp

### 重现链接

https://github.com/nutui-uniapp/nutui-uniapp

### 重现步骤

custom-style 样式重叠

### 期望的结果是什么？

不重叠

### 实际的结果是什么？

重叠

### 其他补充信息

input wrap 的样式 [code link](https://github.com/nutui-uniapp/nutui-uniapp/blob/main/packages/nutui/components/input/input.vue#L205) 与 inner [input ](https://github.com/nutui-uniapp/nutui-uniapp/blob/main/packages/nutui/components/input/input.vue#L214)样式重复样式问题

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/26627486/0c1ea358-2a5f-4cd6-bcdb-dabfa42803c3)

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/26627486/d3c322be-d76f-49f1-86d5-7a9f4811e69d)
```js
<nut-input
    v-model="item.value"
    :border="false"
    :custom-style="{
        'background': '#F1F4F8',
        // 'background': '#F1FFE7',
        // 'border-radius': '20rpx',
        'padding': '2rpx 18rpx',
        'border': '4rpx solid #7AB54D',
        'font-weight': 600,
        'font-size': '52rpx',
        'line-height': '60rpx',
        'color': '#333333',
        'height': '80rpx',
    }"
    placeholder="请输入"
/>
```

**Comment by xiaohe0601** [comment]
后续会拆分出 `input-style`
