### ISSUE TITLE
[FR]: 每个grid-item中的内容背景不能通过custom-class来定义

### ISSUE THREAD

**Issue by charlesluo2014** [nutui-uniapp/nutui-uniapp#232]
### 这个功能解决了什么问题？

.nut-theme-dark .nut-grid-item__content[data-v-b21bfe86] {
    color: var(--nut-dark-color, var(--nut-white, #fff));
    background: var(--nut-dark-background, #131313);
    border: 0 solid var(--nut-dark-background2, #1b1b1b);
}

### 你期望的组件设计是怎样的？

能通过custom-class定义每个item中的背景颜色和padding

**Comment by xiaohe0601** [comment]
目前可以使用如下方式实现

```vue
<template>
  <nut-grid>
    <nut-grid-item custom-class="custom-grid-item" text="文字"></nut-grid-item>
  </nut-grid>
</template>

<style lang="scss">
.custom-grid-item {
  .nut-grid-item__content {
    background-color: red;
  }
}
</style>

<!-- 如果在scoped范围下则使用:deep() -->
<style lang="scss" scoped>
.custom-grid-item {
  :deep(.nut-grid-item__content) {
    background-color: red;
  }
}
</style>
```

至于后续是否能够直接控制content样式，还需要再评估~
