### ISSUE TITLE
Drag 希望能解决推拽出边界问题

### ISSUE THREAD

**Issue by you-hei-mi** [nutui-uniapp/nutui-uniapp#244]
### nutui-uniapp 版本号

1.7.3

### 平台

h5, 其他小程序

### 重现链接

https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/drag

### 重现步骤

Drag 希望能解决推拽出边界问题
https://nutui-uniapp.netlify.app/components/feedback/drag.html

### 期望的结果是什么？

希望 Drag 能与 nutui 4.3.2  Drag 同步
https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/drag

### 实际的结果是什么？

Drag 能与 nutui 4.3.2  Drag 不同步
https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/drag

**Comment by RJQingHuan** [comment]
有`boundary`属性,文档上没写,后续会更新文档
