### ISSUE TITLE
表单组件在微信小程序部分手机上无法显示

### ISSUE THREAD

**Issue by evanwu66** [nutui-uniapp/nutui-uniapp#249]
### nutui-uniapp 版本号

1.17.3

### 平台

weapp

### 重现链接

无

### 重现步骤

`<nut-form ref="addressFormRef" :model-value="addressFormData" :rules="formRules">
        <nut-form-item
          label="姓名"
          prop="name"
          label-width="50"
        >
          <nut-input
            v-model="addressFormData.name"
            placeholder="请输入姓名"
            type="text"
          />
        </nut-form-item>
        <nut-form-item
          label="电话" 
          prop="phone" 
          required
          label-width="50"
        >
          <nut-input v-model="addressFormData.phone" placeholder="请输入联系电话" type="text" label-width="50"/>
        </nut-form-item>
        <nut-form-item
          label="地区"
          prop="region"
          required
          label-width="50"
        >
          <div class="flex items-center" @click="showRegion">
            <nut-input v-model="addressFormData.province" placeholder="省" type="text" :disabled="true" />
            <nut-input v-model="addressFormData.city" placeholder="市" type="text" :disabled="true"/>
            <nut-input v-model="addressFormData.region" placeholder="区" type="text" :disabled="true"/>
          </div>
        </nut-form-item>
        <nut-form-item label="地址" prop="address" required label-width="50">
          <nut-textarea 
            v-model="addressFormData.address" 
            placeholder="请输入详细地址" 
            :autosize="{maxHeight: 100, minHeight: 72}" 
          />
        </nut-form-item>
      </nut-form>`

`const addressFormRef = ref();
  const addressFormData = reactive({
    id: "",
    name: "",
    phone: "",
    province: "",
    provinceCode: "",
    city: "",
    cityCode: "",
    region: "",
    regionCode: "",
    address: "",
    defaultAddress: false,
  });
  const formRules = { 
    name: [
      { required: true, message: '请填写姓名' }
    ],
    phone: [
      { required: true, message: '请填写联系电话' },
      { validator: (val) => phoneValidator(val), message: '电话格式不正确' },
    ],
    region: [{ required: true, message: '请选择地区' }],
    address: [{ required: true, message: '请填写地址' }]
  }
  // 手机号校验
  const phoneValidator = (val: string) => {
    if (/^1[345789]\d{9}\-\d{4,5}$/.test(val) 
      || /^1[3456789]\d{9}$/.test(val)
      || /^0\d{2,3}-?\d{7,8}$/.test(val) 
      || /^400[\d-]{7,13}$/.test(val)) {
      return true;
    } else {
      return false;
    }
  }`

### 期望的结果是什么？

适配所有机型

### 实际的结果是什么？

部分手机在微信小程序上无法显示

**Comment by de1ck** [comment]
@yang1206 
 ihone xr ios 13.6.1 微信 8.0.49 复现 界面报错
 
 <TypeError: Attempted to assign to readonly property.>
set@https://usr//appservice.app.js:59:40376
defineProperty@https://usr//appservice.app.js:59:40695
defineProperty@[native code]
https://usr//appservice.app.js:59:30516
Ur@https://usr//appservice.app.js:59:30562
a@https://usr//appservice.app.js:59:249629
Xc@https://usr//appservice.app.js:59:143006
setup@https://usr//node-modules/nutui-uniapp/components/formitem/formitem.appservice.js:93:453
io@https://usr//appservice.app.js:59:32526
https://usr//appservice.app.js:59:52218
https://usr//appservice.app.js:59:52349
na@https://usr//appservice.app.js:59:52366
https://usr//appservice.app.js:59:66671
attached@https://usr//appservice.app.js:59:66695
https://lib/WASubContext.js:1:207314
https://lib/WASubContext.js:1:207187
t@https://lib/WASubContext.js:1:225682
t@https://lib/WASubContext.js:1:225994
t@https://lib/WASubContext.js:1:225994
t@https://lib/WASubContext.js:1:225994
t@https://lib/WASubContext.js:1:225994
t@https://lib/WASubContext.js:1:225994
t@https://lib/WASubContext.js:1:225994
t@https://lib/WASubContext.js:1:225936
f@https://lib/WASubContext.js:1:226004
https://lib/WASubContext.js:1:238039
vs@https://lib/WASubContext.js:1:435110
https://lib/WASubContext.js:1:488932
https://lib/WASubContext.js:1:452252
https://lib/WASubContext.js:1:493887
https://lib/WASubContext.js:1:452252
https://lib/WASubContext.js:1:495803
https://lib/WASubContext.js:1:452252
Cr@https://lib/WASubContext.js:1:496595
https://lib/WASubContext.js:1:451325
https://lib/WAServiceMainContext.js:1:627165
emitInternal@https://lib/WAServiceMainContext.js:1:632401
aO@https://lib/WAServiceMainContext.js:1:960845
L@https://lib/WAServiceMainContext.js:1:1770036
https://lib/WAServiceMainContext.js:1:1771237
https://lib/WAServiceMainContext.js:1:1002199
https://lib/WAServiceMainContext.js:1:627264
emit@https://lib/WAServiceMainContext.js:1:632309
https://lib/WAServiceMainContext.js:1:633382
https://lib/WAServiceMainContext.js:1:623636
https://lib/WAServiceMainContext.js:1:614363
emit@https://lib/WAServiceMainContext.js:1:119316
emit@[native code]
emit@https://lib/WAServiceMainContext.js:1:118935
subscribeHandler@https://lib/WAServiceMainContext.js:1:122459
global code

**Comment by yang1206** [comment]
> @yang1206 ihone xr ios 13.6.1 微信 8.0.49 复现 界面报错
> 
> <TypeError: Attempted to assign to readonly property.> set@[usr//appservice.app.js:59:40376](https://usr//appservice.app.js:59:40376) defineProperty@[usr//appservice.app.js:59:40695](https://usr//appservice.app.js:59:40695) defineProperty@[native code] [usr//appservice.app.js:59:30516](https://usr//appservice.app.js:59:30516) Ur@[usr//appservice.app.js:59:30562](https://usr//appservice.app.js:59:30562) a@[usr//appservice.app.js:59:249629](https://usr//appservice.app.js:59:249629) Xc@[usr//appservice.app.js:59:143006](https://usr//appservice.app.js:59:143006) setup@[usr//node-modules/nutui-uniapp/components/formitem/formitem.appservice.js:93:453](https://usr//node-modules/nutui-uniapp/components/formitem/formitem.appservice.js:93:453) io@[usr//appservice.app.js:59:32526](https://usr//appservice.app.js:59:32526) [usr//appservice.app.js:59:52218](https://usr//appservice.app.js:59:52218) [usr//appservice.app.js:59:52349](https://usr//appservice.app.js:59:52349) na@[usr//appservice.app.js:59:52366](https://usr//appservice.app.js:59:52366) [usr//appservice.app.js:59:66671](https://usr//appservice.app.js:59:66671) attached@[usr//appservice.app.js:59:66695](https://usr//appservice.app.js:59:66695) [lib/WASubContext.js:1:207314](https://lib/WASubContext.js:1:207314) [lib/WASubContext.js:1:207187](https://lib/WASubContext.js:1:207187) t@[lib/WASubContext.js:1:225682](https://lib/WASubContext.js:1:225682) t@[lib/WASubContext.js:1:225994](https://lib/WASubContext.js:1:225994) t@[lib/WASubContext.js:1:225994](https://lib/WASubContext.js:1:225994) t@[lib/WASubContext.js:1:225994](https://lib/WASubContext.js:1:225994) t@[lib/WASubContext.js:1:225994](https://lib/WASubContext.js:1:225994) t@[lib/WASubContext.js:1:225994](https://lib/WASubContext.js:1:225994) t@[lib/WASubContext.js:1:225994](https://lib/WASubContext.js:1:225994) t@[lib/WASubContext.js:1:225936](https://lib/WASubContext.js:1:225936) f@[lib/WASubContext.js:1:226004](https://lib/WASubContext.js:1:226004) [lib/WASubContext.js:1:238039](https://lib/WASubContext.js:1:238039) vs@[lib/WASubContext.js:1:435110](https://lib/WASubContext.js:1:435110) [lib/WASubContext.js:1:488932](https://lib/WASubContext.js:1:488932) [lib/WASubContext.js:1:452252](https://lib/WASubContext.js:1:452252) [lib/WASubContext.js:1:493887](https://lib/WASubContext.js:1:493887) [lib/WASubContext.js:1:452252](https://lib/WASubContext.js:1:452252) [lib/WASubContext.js:1:495803](https://lib/WASubContext.js:1:495803) [lib/WASubContext.js:1:452252](https://lib/WASubContext.js:1:452252) Cr@[lib/WASubContext.js:1:496595](https://lib/WASubContext.js:1:496595) [lib/WASubContext.js:1:451325](https://lib/WASubContext.js:1:451325) [lib/WAServiceMainContext.js:1:627165](https://lib/WAServiceMainContext.js:1:627165) emitInternal@[lib/WAServiceMainContext.js:1:632401](https://lib/WAServiceMainContext.js:1:632401) aO@[lib/WAServiceMainContext.js:1:960845](https://lib/WAServiceMainContext.js:1:960845) L@[lib/WAServiceMainContext.js:1:1770036](https://lib/WAServiceMainContext.js:1:1770036) [lib/WAServiceMainContext.js:1:1771237](https://lib/WAServiceMainContext.js:1:1771237) [lib/WAServiceMainContext.js:1:1002199](https://lib/WAServiceMainContext.js:1:1002199) [lib/WAServiceMainContext.js:1:627264](https://lib/WAServiceMainContext.js:1:627264) emit@[lib/WAServiceMainContext.js:1:632309](https://lib/WAServiceMainContext.js:1:632309) [lib/WAServiceMainContext.js:1:633382](https://lib/WAServiceMainContext.js:1:633382) [lib/WAServiceMainContext.js:1:623636](https://lib/WAServiceMainContext.js:1:623636) [lib/WAServiceMainContext.js:1:614363](https://lib/WAServiceMainContext.js:1:614363) emit@[lib/WAServiceMainContext.js:1:119316](https://lib/WAServiceMainContext.js:1:119316) emit@[native code] emit@[lib/WAServiceMainContext.js:1:118935](https://lib/WAServiceMainContext.js:1:118935) subscribeHandler@[lib/WAServiceMainContext.js:1:122459](https://lib/WAServiceMainContext.js:1:122459) global code

请提供最小复现demo

**Comment by yang1206** [comment]
> @yang1206 [github demo](https://github.com/de1ck/nutui-uniapp-demo/tree/de1ck/patch-30500?rgh-link-date=2024-04-29T09%3A27%3A44Z)

<img width="234" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/28709596/8aa6a713-ee4b-458a-875e-e979f3415cca">

没有复现，请提供你的环境信息

**Comment by de1ck** [comment]
> ihone xr ios 13.6.1 微信 8.0.49 复现 界面报错

ihone xr ios 13.6.1 微信 8.0.49 复现 界面报错

**Comment by evanwu66** [comment]
在部分手机上出现，redio直接不显示，非常恐怖，换成uni-ui的form正常，另外在windows的微信上打开小程序，弹窗也无法弹出

**Comment by yang1206** [comment]
请按照 issue 模板的提示提供对应的环境信息，你目前提供的信息对解决问题没有任何帮助
<img width="929" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/28709596/f1f7966c-66a8-42bf-b820-ea168ccc650a">

**Comment by xh12** [comment]
同样问题，修改打包方式，去掉严格模式 可以解决， 在vite 配置中使用  `@vitejs/plugin-legacy` 这个插件，配置如下
 `   legacy({  
      targets: ['ie >= 11'], // 根据需要设置目标浏览器  
      additionalLegacyPolyfills: ['regenerator-runtime/runtime'], // 可能需要的其他 polyfills  
      renderModernChunks: false,
    }),  `
