### ISSUE TITLE
[FR]: 二次开发需求

### ISSUE THREAD

**Issue by hhnbwqq** [nutui-uniapp/nutui-uniapp#255]
### 这个功能解决了什么问题？

我这边是cli项目，想基于这套框架进行二次开发，但是目前找到的方式只有npm引入和uni_modules两种，请问能不能提供可以二次开发的方式

### 你期望的组件设计是怎样的？

如上

**Comment by hhnbwqq** [comment]
我想把组件下载下来，并且能够进行修改，node_modules里的不是不允许改动么？

**Comment by xiaohe0601** [comment]
cli也可以用uni_modules的方式去使用，下载到项目过后自行修改就行

**Comment by hhnbwqq** [comment]
好的，麻烦uniapp插件市场更新下，我看目前还是1.6.9

**Comment by yang1206** [comment]
已发布更新
