### ISSUE TITLE
运行至微信小程序样式穿透未生效

### ISSUE THREAD

**Issue by boss-zhu** [nutui-uniapp/nutui-uniapp#256]
### nutui-uniapp 版本号

1.7.3

### 平台

其他小程序

### 重现链接

无链接

### 重现步骤

添加class类名后，进行css设置，但微信小程序中样式设置未生效，h5则生效.
下方进行box-shadow清除
```
<template>
  <view class="custom">
    <view class="width"></view>
    <nut-menu class="menu">
      <nut-menu-item v-model="value1" :options="options1" />
    </nut-menu>
  </view>
</template>

<script>
import { defineComponent, reactive, toRefs } from 'vue';

export default defineComponent({
  name: 'Test',
  setup() {
    const state = reactive({
      value1: 0,
      options1: [
        { text: '全部商品', value: 0 },
        { text: '新款商品', value: 1 },
        { text: '活动商品', value: 2 }
      ],
    });
    const handleChange = val => {
      console.log('val', val);
    }
    return {
      ...toRefs(state),
      handleChange,
    };
  },
});
</script>

<style scoped lang="scss">
.custom {
  display: flex;
  .width {
    width: 100upx;
  }
  .menu {
    :deep(.nut-menu__bar) {
      box-shadow: none;
    }
  }
}
</style>

```

### 期望的结果是什么？

微信小程序样式穿透生效

### 实际的结果是什么？

微信小程序样式穿透未生效

**Comment by boss-zhu** [comment]
微信小程序执行：
<img width="411" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/80495758/ac70355c-4e13-4253-b219-9f10acc7ac21">
h5执行
<img width="412" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/80495758/247d1f8b-1258-48f2-8de4-1dc1376d8b3f">

**Comment by xiaohe0601** [comment]
[自定义组件的 style 或 class](https://uniapp-nutui.tech/guide/theme.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E7%9A%84-style-%E6%88%96-class)
