### ISSUE TITLE
input输入框当type为number类型时无效

### ISSUE THREAD

**Issue by YHoney7** [nutui-uniapp/nutui-uniapp#278]
### nutui-uniapp 版本号

latest

### 平台

h5, weapp

### 重现链接

文档上即可复现

### 重现步骤

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/49771966/ca19f612-27c9-4378-a06a-f12b912e7c51)

### 期望的结果是什么？

只能输入数字

### 实际的结果是什么？

输入中文依然有效

**Comment by YHoney7** [comment]
同时也测试了searchbar, 当input-type为number/digit类型时, 也可以输入中文

**Comment by YHoney7** [comment]
补充微信小程序
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/49771966/99dcf2d9-af7a-4718-9f97-e9bb858c9453)

**Comment by xiaohe0601** [comment]
H5端问题确认，已修复，小程序端请以真机为准
