### ISSUE TITLE
微信小程序和APP使用swipe组件会存在样式问题

### ISSUE THREAD

**Issue by YHoney7** [nutui-uniapp/nutui-uniapp#281]
### nutui-uniapp 版本号

1.7.5

### 平台

weapp, 其他小程序

### 重现链接

如下

### 重现步骤

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/49771966/537a683f-df1d-49e7-9fd8-bc0fc84cbc29)
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/49771966/4520d509-7efb-4d71-8b70-dac8b173e866)
在swiper存在right插槽时, 页面上下滚动会显示横线滚动条

### 期望的结果是什么？

不存在横向滚动条

### 实际的结果是什么？

存在横向滚动条

**Comment by YHoney7** [comment]
补充一下, 如果把right插槽注释掉, 就不会存在这个问题

**Comment by YHoney7** [comment]
您好，想问下, 这个BUG修复完毕后, 下次发版是什么时候呢

**Comment by xiaohe0601** [comment]
预计今天会更新
