### ISSUE TITLE
Ecard虚拟电子卡

### ISSUE THREAD

**Issue by lihu12320** [nutui-uniapp/nutui-uniapp#283]
### nutui-uniapp 版本号

1.5.3

### 平台

weapp, 其他小程序

### 重现链接

https://uniapp-nutui.tech/components/business/ecard.html

### 重现步骤

![01](https://github.com/nutui-uniapp/nutui-uniapp/assets/83901426/a9a71938-79b5-4b2b-9c71-e9daa001b0de)

### 期望的结果是什么？

其他面值和下面的数字保持一致

### 实际的结果是什么？

没有保持一致，(https://uniapp-nutui.tech/components/business/ecard.html) 官方上可以直接重现

**Comment by YHoney7** [comment]
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/49771966/826ec7e2-dee6-41fe-858d-326381725aa8)
因为面值最大默认为9999

**Comment by lihu12320** [comment]
在其他面值和下面都需要限制，上下不应该保持一致么？上面输入9999999999999999下边虽然限制了但输入框没限制，现在是需要都限制。h5组件都有这个限制https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/ecard。

**Comment by lihu12320** [comment]
![5](https://github.com/nutui-uniapp/nutui-uniapp/assets/83901426/867c722e-5051-42d8-b59f-5b2bb47a6df5)
