### ISSUE TITLE
[FR]: 关于升级vue版本为vue3.4x

### ISSUE THREAD

**Issue by 851091009** [nutui-uniapp/nutui-uniapp#287]
### 这个功能解决了什么问题？

uniapp 已经升级为 vue3.4x ，咱们这边是否有计划安排升级，谢谢。

### 你期望的组件设计是怎样的？

无

**Comment by xiaohe0601** [comment]
可以继续使用，后续会调整 `peerDependencies`

**Comment by 851091009** [comment]
好的
