### ISSUE TITLE
[FR]: navbar和tabs能不能支持透明效果

### ISSUE THREAD

**Issue by charlesluo2014** [nutui-uniapp/nutui-uniapp#290]
### 这个功能解决了什么问题？

在开发视频的时候，需要视频顶部navbar透明，假如navbar添加tabs，tabs也需要透明

### 你期望的组件设计是怎样的？

在开发视频的时候，需要视频顶部navbar透明，假如navbar添加tabs，tabs也需要透明

**Comment by xiaohe0601** [comment]
建议自行使用css修改~
