### ISSUE TITLE
[FR]: sku组件不支持主动修改 skustepper的input-number值

### ISSUE THREAD

**Issue by xskjs888** [nutui-uniapp/nutui-uniapp#296]
### 这个功能解决了什么问题？

在更改商品规格之后，希望能够主动修改数量为1。目前不修改源码，好像实现不了。组件没有暴露方法

### 你期望的组件设计是怎样的？

能够提供一个修改input-number的值

**Comment by yang1206** [comment]
可以增加一个方法，欢迎 pr
