### ISSUE TITLE
无法在Tabs 选项卡切换中使用，ActionSheet、Menu类的弹窗组件

### ISSUE THREAD

**Issue by madehua** [nutui-uniapp/nutui-uniapp#302]
### nutui-uniapp 版本号

1.7.7

### 平台

h5, weapp

### 重现链接

https://github.com/madehua/nutui-datepicker-demo/blob/main/src/pages/nutui/tabs/tabs.vue

### 重现步骤

1、点击tabs按钮
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/fcf887b1-60e9-4b30-991b-91494feba027)
2、点击tab2选项
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/43953e01-cbf8-41c0-9077-fc05341f6914)
3、点击基础用法
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/d1f814a2-c73b-451d-a4b4-54182c31d288)

### 期望的结果是什么？

可以在页面底部弹窗

### 实际的结果是什么？

在第一个选项卡面板中渲染。
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/7ed42603-791c-4b30-b0b9-80b1c8dafbd9)

**Comment by xiaohe0601** [comment]
tabs组件使用了 `transform` 会影响内部的 `fixed` 元素，由于uniapp不支持 [Teleport](https://uniapp.dcloud.net.cn/tutorial/vue3-basics.html#%E5%9C%A8-uni-app-%E4%B8%AD%E4%BD%BF%E7%94%A8vue%E7%9A%84%E5%B7%AE%E5%BC%82) 组件，所以请手动将 `fixed` 元素写到tabs外部

```html
<template>
  <nut-tabs>
    <nut-tab-pane title="Tab 1">
      Tab 1
    </nut-tab-pane>

    <nut-tab-pane title="Tab 2">
      Tab 2
    </nut-tab-pane>
  </nut-tabs>

  <nut-action-sheet></nut-action-sheet>
</template>
```
