### ISSUE TITLE
nut-popup在支付宝小程序上样式丢失

### ISSUE THREAD

**Issue by cqzhong** [nutui-uniapp/nutui-uniapp#304]
### nutui-uniapp 版本号

1.7.7

### 平台

alipay

### 重现链接

无

### 重现步骤

使用nut-popup写一个弹窗组件，在支付宝小程序平台，样式丢失。

### 期望的结果是什么？

h5 和微信小程序样式正确。
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/10128830/254c239e-a2a8-4f2f-889c-ee2517a151bd)

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/10128830/8858d2de-461e-4e8d-9877-0e28cd7c32fa)

### 实际的结果是什么？

支付宝样式错误
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/10128830/9a29af95-59b3-42b2-80c8-10a16b5b4ce0)

### 环境信息

# uniapp的版本：
- 4.08.2024040123
- 4.07.2024032720
- 4.06.2024032513
- 3.99.2023122611

# 系统信息
  System:
    OS: macOS 14.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 1.01 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.13.2 - ~/node_modules/.bin/npm
    pnpm: 8.6.5 - /usr/local/bin/pnpm
    Watchman: 2023.06.26.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 124.0.6367.60
    Safari: 17.2.1

### 其他补充信息

使用uniapp版本 4.08.2024040123、4.07.2024032720、4.06.2024032513、3.99.2023122611 支付宝小程序样式丢失，使用`"@dcloudio/uni-app": "3.0.0-3090820231124001"`这个版本支付宝小程序样式展示正确

**Comment by yang1206** [comment]
这是一个已知问题， 我也不知道为什么在支付宝小程序会编译成这样😵‍💫， 可以看一下文档中注意事项，有解决办法

**Comment by xiaohe0601** [comment]
`uniapp`  自 `3.99.2023122611` 开始新增了支付宝小程序的 `styleIsolation` 配置，默认值由 `shared` 调整为 `apply-shared`，导致嵌套组件样式异常，并且目前不支持单独组件修改配置，这属于 `uniapp` 方面的破坏性变更

现在只能先手动在 `manifest.json` 中的 `mp-alipay` 字段下添加 `styleIsolation` 配置，将默认值重置为 `shared`，等 `uniapp` 后续支持单独配置后，组件内部再跟进修改

```json
{
  "mp-alipay": {
    "usingComponents": true,
    "styleIsolation": "shared"
  }
}
```
