### ISSUE TITLE
nut-checkbox nut-radio 功能建议

### ISSUE THREAD

**Issue by liniu** [nutui-uniapp/nutui-uniapp#308]
### 这个功能解决了什么问题？

选项值并非true或false，可能是1或0 ，或者其他字符串。

### 你期望的组件设计是怎样的？

类似switch 的active-value和inactive-value,为checkbox和radio 增加true-value，false-value，默认值分别为true 和false, 可以自定义
可能是1或0 ，或者其他字符串。增加组件的易用性。

**Comment by liniu** [comment]
老大，这个什么时候安排一下，v-model或选项值并非true或false，可能是1或0 ，或者其他字符串的场景很多啊。

**Comment by xiaohe0601** [comment]
`nut-radio` 不支持单独使用，只能配合 `nut-radio-group` 使用，是支持通过 `label` 传递 `number` `string` `boolean` 类型参数的，`nut-checkbox` 配合 `nut-checkbox-group` 使用的时候也支持。

至于 `nut-checkbox` 单独使用的时候，后续添加一下吧，也欢迎PR😀
