### ISSUE TITLE
微信小程序 Input clear 点击清除按钮清除不了输入框数据

### ISSUE THREAD

**Issue by de1ck** [nutui-uniapp/nutui-uniapp#309]
### nutui-uniapp 版本号

1.7.8

### 平台

weapp

### 重现链接

https://github.com/de1ck/nutui-uniapp-demo/tree/issue-input

### 重现步骤

```vue
<script setup lang="ts">
import { ref } from 'vue'

const name = ref('')
</script>

<template>
  <view class="content">
    <nut-input v-model="name" custom-class="input-wrap" placeholder="请输入姓名" type="text" :max-length="9" clearable />
  </view>
</template>

<style>
.content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
</style>

```

### 期望的结果是什么？

可以清除

### 实际的结果是什么？

不能清除

### 环境信息

微信： 8.0.49 
设备：ios 17.4.1

**Comment by xiaohe0601** [comment]
可以清除，但是图标不好点击到，会优化一下

**Comment by NoahSun** [comment]
> 可以清除，但是图标不好点击到，会优化一下

ui版本：1.7.10
机型：小米mix4（hyper os 1.0.2.0.UKMCNXM）Android14
微信版本：8.0.49

在微信开发者工具上结果是正确的。

在手机上点击清除图标，实测先触发clear，再触发blur，再触发update:modelValue，这时会把blur中得到的值传给update:modelValue，导致需要点很多次才能清除
