### ISSUE TITLE
Popup 弹出层

### ISSUE THREAD

**Issue by Li-Fengxin** [nutui-uniapp/nutui-uniapp#313]
### nutui-uniapp 版本号

1.7.8

### 平台

h5

### 重现链接

https://uniapp-nutui.tech/components/basic/popup.html

### 重现步骤

代码中 
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/25520018/56ba9256-53e7-4e26-8c8e-3b3139c509c6)
含有实际回调参数的Events，与文档所示内容不符。
另，在点击close-icon，触发Events(click-close-icon，close)之后无法阻止Popup关闭。 请问是否有方式可以在点击close-icon阻止Popup的关闭。

### 期望的结果是什么？

1.  文档与实际代码相符合
2.  点击close-icon之后在某种情况下阻止Popup的关闭。

### 实际的结果是什么？

1.  部分Events无回调参数
2. 在点击close-icon，触发Events(click-close-icon，close)之后无法阻止Popup关闭。

**Comment by yang1206** [comment]
close-icon事件会触发关闭，这是正常的行为，如果想阻止 Popup关闭可以通过visible属性和 update:visible事件实现，具体可以参考[这里](https://uniapp-nutui.tech/components/feedback/switch.html#%E5%BC%82%E6%AD%A5%E6%8E%A7%E5%88%B6)
