### ISSUE TITLE
签名组件报错

### ISSUE THREAD

**Issue by pistolGit** [nutui-uniapp/nutui-uniapp#314]
### nutui-uniapp 版本号

1.7.8

### 平台

h5

### 重现链接

https://uniapp-nutui.tech/components/business/signature.html

### 重现步骤

官网上的例子就无法使用

### 期望的结果是什么？

无法使用

### 实际的结果是什么？

h5和APP端均可使用

**Comment by xiaohe0601** [comment]
这是uniapp内部缺陷，升级uniapp版本即可 [uniapp 4.15.2024050802](https://uniapp.dcloud.net.cn/release.html#_4-15-2024050802)
