### ISSUE TITLE
选择时间一直返回00:00

### ISSUE THREAD

**Issue by sunday-ma** [nutui-uniapp/nutui-uniapp#317]
### nutui-uniapp 版本号

1.7.10

### 平台

weapp

### 重现链接

只有图片

### 重现步骤

const collectionTime = ref('')
function setCollectionTimeValue(param: DatePickerBaseEvent) {
  console.log('setCollectionTimeValue', param)
}
<nut-date-picker
    v-model="collectionTime"
    type="hour-minute"
    title="时间选择"
    @confirm="setCollectionTimeValue"
    @cancel="collectionTimeIsVisible = false"
  />

### 期望的结果是什么？

selectedValue: {0: '09', 1: '00'}

### 实际的结果是什么？

![图片](https://github.com/nutui-uniapp/nutui-uniapp/assets/165110532/97000164-e948-43d6-90bf-1d23bd9c557e)

### 环境信息

System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 16.74 GB / 31.90 GB
  Binaries:
    Node: 20.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.0 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.1.7 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    nutui-uniapp: ^1.7.10 => 1.7.10

**Comment by sunday-ma** [comment]
change事件能正确获取到数据

**Comment by sunday-ma** [comment]
change事件中的columnIndex一直是0

**Comment by xiaohe0601** [comment]
绑定值的默认值不能是空字符串，可以是 `Date`、`number`(13位时间戳)、`null`、`undefined`
