### ISSUE TITLE
项目启动时编译文件出错

### ISSUE THREAD

**Issue by xiaoLee9547** [nutui-uniapp/nutui-uniapp#327]
### nutui-uniapp 版本号

1.7.10

### 平台

weapp

### 重现链接

https://github.com/xiaoLee9547/nutui-mini-respository

### 重现步骤

按照文档进行安装

### 期望的结果是什么？

正确编译

### 实际的结果是什么？

![log](https://github.com/nutui-uniapp/nutui-uniapp/assets/132629779/c39bd925-8047-4991-9e5d-49988a6ce304)

**Comment by xiaohe0601** [comment]
`App.vue` 的 `<style` 添加 `lang="scss"`

[样式引入](https://uniapp-nutui.tech/guide/quick-start.html#%E6%A0%B7%E5%BC%8F%E5%BC%95%E5%85%A5)
