### ISSUE TITLE
[plugin:uni:mp-using-component] Expected ',' or '}' after property value in JSON at position 25

### ISSUE THREAD

**Issue by xolee** [nutui-uniapp/nutui-uniapp#341]
### nutui-uniapp 版本号

1.7.10

### 平台

weapp

### 重现链接

https://github.com/xolee/issues

### 重现步骤

使用 unplugin 和 easycom 两种方式，都会初夏下面的报错
```
[plugin:uni:mp-using-component] Expected ',' or '}' after property value in JSON at position 25
at ../node_modules/nutui-uniapp/components/button/button.vue:1:0
```

### 期望的结果是什么？

正确安装

### 实际的结果是什么？

如上

### 环境信息

  System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
    Memory: 1.51 GB / 7.88 GB
  Binaries:
    Node: 20.12.2 - C:\laragon\bin\nodejs\node-v20.12.2-win-x64\node.EXE
    npm: 10.5.2 - C:\laragon\bin\nodejs\node-v20.12.2-win-x64\npm.CMD
    pnpm: 9.0.1 - C:\laragon\bin\nodejs\node-v20.12.2-win-x64\pnpm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.79)
    Internet Explorer: 11.0.22621.3520
  npmPackages:
    nutui-uniapp: ^1.7.10 => 1.7.10

**Comment by xiaohe0601** [comment]
请先将uniapp的版本回调至 `3.0.0-4000820240401001`，具体问题还需要再排查~

**Comment by xiaohe0601** [comment]
https://github.com/dcloudio/uni-app/issues/4964

**Comment by Qthon** [comment]
> 请先将uniapp的版本回调至 `3.0.0-4000820240401001`，具体问题还需要再排查~

回退后，会编译失败
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/57051723/92e5a889-bf00-4795-b5c0-86ca872240be)

**Comment by xiaohe0601** [comment]
> [dcloudio/uni-app#4964](https://github.com/dcloudio/uni-app/issues/4964)

@Qthon 回退uniapp版本后需要同时回退pinia版本为2.0.x，如果不想回退版本，请参考这个issue中的临时解决方案，或者等uniapp后续更新版本修复

**Comment by xolee** [comment]
3.0.0-alpha-4010920240606001

已修复该问题
