### ISSUE TITLE
swiper 加载页面闪烁

### ISSUE THREAD

**Issue by madehua** [nutui-uniapp/nutui-uniapp#344]
### nutui-uniapp 版本号

1.7.10

### 平台

weapp

### 重现链接

https://github.com/madehua/nutui-datepicker-demo/blob/main/src/pages/nutui/swiper/swiper.vue

### 重现步骤

代码片段:
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/f70d77ef-9a66-4cc4-8832-3ad6e396f8e1)

微信小程序，先把nut-swiper-item显示出来，在显示第一个nut-swiper-item出现闪屏现象，H5端正常。
<img width="211" alt="1717744922365" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/f87c7af7-1707-4407-a477-2a7515dcbe93">
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/16407351/4d53651c-655f-4db2-9b3d-19d7f2237eee)

### 期望的结果是什么？

正常显示

### 实际的结果是什么？

先显示所有nut-swiper-item页面，在显示第一页。

### 环境信息

System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 1.84 GB / 15.73 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (113.0.1774.42)
    Internet Explorer: 11.0.22621.3527

**Comment by yang1206** [comment]
没看明白你的问题，可以提供一个复现的仓库吗

**Comment by madehua** [comment]
demo地址：https://github.com/madehua/nutui-datepicker-demo
具体代码地址：
https://github.com/madehua/nutui-datepicker-demo/blob/main/src/pages/nutui/swiper/swiper.vue

**Comment by madehua** [comment]
> 没看明白你的问题，可以提供一个复现的仓库吗

swiper在微信小程序中，加载过程把swiper-item显示在了一屏了。闪了一下就正常显示第一个swiper-item内容。

**Comment by yang1206** [comment]
这与异步状态有关，你可以使用 v-if在 list.length > 0时才显示swiper-item
