### ISSUE TITLE
uniapp版本的组件文档有新的么？

### ISSUE THREAD

**Issue by dreams-iP** [nutui-uniapp/nutui-uniapp#353]
### nutui-uniapp 版本号

1.7.10

### 平台

weapp

### 重现链接

https://uniapp-nutui.tech/components/nav/tabbar.html

### 重现步骤

用了几个组件 但是部分参数啥的都不对，基本都要去组件代码里面去翻现在新的是什么参数。。。。

### 期望的结果是什么？

文档参数对的上

### 实际的结果是什么？

文档参数不对

### 其他补充信息

可不可以麻烦老哥们更新以下新的文档呢，或许是我找错地址了，如果有新的文档参考地址的话麻烦回复下呢

**Comment by dreams-iP** [comment]
例如 tabbar组件里面有个v-model，现在新的参数实际是modelValue，

**Comment by RJQingHuan** [comment]
> 例如 tabbar组件里面有个v-model，现在新的参数实际是modelValue，

v-model和modelValue是一个意思的。看一下[vue文档](https://cn.vuejs.org/guide/components/v-model.html#under-the-hood)
