### ISSUE TITLE
picker选择之后更换数据源，得到错误值

### ISSUE THREAD

**Issue by xiaoLee9547** [nutui-uniapp/nutui-uniapp#355]
### nutui-uniapp 版本号

1.7.10

### 平台

weapp

### 重现链接

https://github.com/xiaoLee9547/nut-mini-problem

### 重现步骤

1. 选择最开始的columns里的某一项
2. 在confirm事件中更换colums数据源
3. 再次唤起Picker,不滑动索引，点击confirm 

### 期望的结果是什么？

得到正确的值

### 实际的结果是什么？

得到第一次选择的value

**Comment by xiaoLee9547** [comment]
目前我的解决方案是在usePicker中监听columns的变化进行重置
`watch(
    () => props.columns,
    (value) => {
      state.formattedColumns = value
      defaultValues.value = []
    },
  )`

**Comment by yang1206** [comment]
从回调中参数的selectedOptions中取值即可

**Comment by xiaoLee9547** [comment]
但是v-model的值也是defaultValue的返回值
