### ISSUE TITLE
Input组件微信小程序清空功能异常

### ISSUE THREAD

**Issue by 74jian** [nutui-uniapp/nutui-uniapp#363]
### nutui-uniapp 版本号

1.7.10

### 平台

weapp

### 重现链接

https://github.com/nutui-uniapp/nutui-uniapp/blob/25fc6a12fa943fd1b6c233dc15b529867fd03446/packages/nutui/components/input/input.vue#L123

### 重现步骤

在微信小程序端中，失去焦点触发[updateValue](https://github.com/nutui-uniapp/nutui-uniapp/blob/25fc6a12fa943fd1b6c233dc15b529867fd03446/packages/nutui/components/input/input.vue#L123)会在清空方法[handleClear](https://github.com/nutui-uniapp/nutui-uniapp/blob/25fc6a12fa943fd1b6c233dc15b529867fd03446/packages/nutui/components/input/input.vue#L136)之后执行，导致清空之后会被重新赋值
![Screen_Recording_20240628_112126_WeChat_1 (1)](https://github.com/nutui-uniapp/nutui-uniapp/assets/15693333/bf5d2d47-57a6-49ba-8cb8-63487b0571aa)

### 期望的结果是什么？

微信小程序端Input组件清空功能正常

### 实际的结果是什么？

清空功能异常

**Comment by xiaohe0601** [comment]
#324 下个版本修复

**Comment by xiaohe0601** [comment]
`1.7.12` 已修复
