### ISSUE TITLE
Navbar自定义左侧插槽箭头高度不一致问题

### ISSUE THREAD

**Issue by qd-xiaowang** [nutui-uniapp/nutui-uniapp#365]
### nutui-uniapp 版本号

1.7.10

### 平台

weapp, 其他小程序

### 重现链接

https://github.com/nutui-uniapp/nutui-uniapp/blob/main/docs/components/nav/navbar.md

### 重现步骤

```html
  <nut-navbar custom-class="mt-20px" title="Title">
    <template #left>
      <nut-icon name="left" /> Back
    </template>
  </nut-navbar>
```

### 期望的结果是什么？

``<``箭头与文字对齐

虽然示例代码非常简洁，但直接复制代码的话，可能会给使用者带来不严谨的感受
![Snipaste_2024-07-03_22-19-17](https://github.com/nutui-uniapp/nutui-uniapp/assets/64092346/d8fcd438-19d7-4914-86d4-5d7e35ab206e)

### 实际的结果是什么？

``<``箭头与文字高度不一致

**Comment by xiaohe0601** [comment]
这是由于uniapp中的插槽编译成小程序时会多一级空白的 `view` 导致的，这与 H5 端表现不一致，为了更好的多端兼容性，需要手动为插槽中的内容包裹一层 `view` 并通过样式设置对齐，感谢反馈，后续会更新文档说明

```html
<template>
  <nut-navbar>
    <template #left>
      <!-- 以unocss举例 -->
      <view class="flex items-center">
        <nut-icon name="left"></nut-icon>
        <text>Back</text>
      </view>
    </template>
  </nut-navbar>
</template>
```
