### ISSUE TITLE
官网域名挂了？

### ISSUE THREAD

**Issue by cnhuye** [nutui-uniapp/nutui-uniapp#367]
### nutui-uniapp 版本号

1

### 平台

weapp

### 重现链接

https://uniapp-nutui.tech/lander

### 重现步骤

官网打不开了，显示 ：

[This domain name has expired. If you are the registered holder of this name and wish to renew it, please contact your registration service provider.](http://uniapp-nutui.tech/)

### 期望的结果是什么？

正常打开

### 实际的结果是什么？

显示域名过期

**Comment by xiaohe0601** [comment]
https://nutui-uniapp.netlify.app

**Comment by qd-xiaowang** [comment]
我也是访问不了，发现域名过期了，汗

**Comment by BG7ZAG** [comment]
该域名了，建议作者去uniapp那边同步改下文档上的连接~

**Comment by xiaohe0601** [comment]
@yang1206 更新一下插件市场吧
