### ISSUE TITLE
TabbarItem 的样式报 Warning

### ISSUE THREAD

**Issue by neatstudio** [nutui-uniapp/nutui-uniapp#373]
### nutui-uniapp 版本号

1.7.12

### 平台

weapp

### 重现链接

无

### 重现步骤

添加 <nut-tabbar><nut-tabbar-item>后，在开发者工具里显示 warning

<img width="805" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/229186/e540b2cf-8793-4aa6-aaf9-be5ac914ad23">

### 期望的结果是什么？

尽量不要出现 warning。虽然我知道这种比较麻烦，但还是希望能没有 Warning 最好

### 实际的结果是什么？

无

**Comment by xiaohe0601** [comment]
这里是为了方便使用 `slot` 自定义图片的时候限制图片大小，如果去掉的话需要开发者手动指定每个图片的大小

**Comment by neatstudio** [comment]
能明白也能理解。image这种非标的tag确实很纠结
