### ISSUE TITLE
menu中的scroll-fixed设置无效

### ISSUE THREAD

**Issue by prometheus-alien** [nutui-uniapp/nutui-uniapp#375]
### nutui-uniapp 版本号

1.7.12

### 平台

h5, weapp

### 重现链接

无

### 重现步骤

给menu设置scroll-fixed无效

### 期望的结果是什么？

scroll-fixed生效

### 实际的结果是什么？

scroll-fixed无效

### 其他补充信息

原因是setup中的onPageScroll无效，在微信小程序和H5中都如此。已确定是页面滚动且高度达到滚动标准。
至于为何无效，是因为setup中的代码是动态执行的，而onPageScroll不能被动态添加，所以不生效。
解决方案：
参考链接：https://ask.dcloud.net.cn/question/136635
在页面中增加单独的onPageScroll非setup定义即可。
`<script>
export default {
  onPageScroll () {
  }
}
</script>`

以上代码，添加到引入官方menu组件的页面即可(若官方没有修复，也无需修改官方组件)。

**Comment by xiaohe0601** [comment]
感谢反馈，目前可以通过你所提供的方案暂时解决，后续会考虑添加参数以供用户手动传入 `scrollTop`

**Comment by prometheus-alien** [comment]
> 感谢反馈，目前可以通过你所提供的方案暂时解决，后续会考虑添加参数以供用户手动传入 `scrollTop`

好的，辛苦了
