### ISSUE TITLE
1.7.12运行支付宝小程序时Failed to compile

### ISSUE THREAD

**Issue by cqshenao** [nutui-uniapp/nutui-uniapp#378]
### nutui-uniapp 版本号

1.7.12

### 平台

alipay

### 重现链接

无

### 重现步骤

![1722220894612](https://github.com/user-attachments/assets/f788575b-0efb-44c3-ace4-8d021a5c8bec)

### 期望的结果是什么？

支付宝小程序正常运行

### 实际的结果是什么？

支付宝小程序Failed to compli

### 其他补充信息

vue3

**Comment by cqshenao** [comment]
微信小程序可以正常显示，支付宝小程序不行

**Comment by xiaohe0601** [comment]
`avatar` 组件使用到了支付宝小程序不支持的 `??` 语法，下个版本将会处理，感谢反馈

**Comment by xiaohe0601** [comment]
`1.7.13` 已修复
