### ISSUE TITLE
[FR]: <nut-cell>关于icon支持图片直接引用，大小

### ISSUE THREAD

**Issue by xlstyle** [nutui-uniapp/nutui-uniapp#383]
### 这个功能解决了什么问题？

 <nut-cell title="我的订单" is-link>
                <template v-slot:icon>
                    <nut-icon name="order"/>
                </template>
            </nut-cell> icon必须写v-slot才能使用，能不 <nut-cell title="我的订单" is-link icon="order">文档是说支持，但没有效果，另外看可以不可以加入icon的大小控制，且支持引入图片，最好<nut-cell title="我的订单" is-link icon="/static/order.png" iconSize="40">

### 你期望的组件设计是怎样的？

 <nut-cell title="我的订单" is-link>
                <template v-slot:icon>
                    <nut-icon name="order"/>
                </template>
            </nut-cell> icon必须写v-slot才能使用，能不 <nut-cell title="我的订单" is-link icon="order">文档是说支持，但没有效果，另外看可以不可以加入icon的大小控制，且支持引入图片，最好<nut-cell title="我的订单" is-link icon="/static/order.png" iconSize="40">

**Comment by xiaohe0601** [comment]
文档描述错误，目前仅支持通过 `icon` slot自定义图标，后续会添加 `icon` 属性，但是如果需要自定义大小颜色等样式还是建议使用slot修改

```html
<nut-cell>
  <template #icon>
    <nut-icon name="my"></nut-icon>
  </template>
</nut-cell>
```
