### ISSUE TITLE
unplugin的方式无法获得组件的类型提示,通过修改global.d.ts和降级vue-official可以勉强解决

### ISSUE THREAD

**Issue by Caffeine19** [nutui-uniapp/nutui-uniapp#405]
### nutui-uniapp 版本号

1.7.14

### 平台

h5

### 重现链接

https://github.com/Caffeine19/uni-ts-test

### 重现步骤

1. 按照官网的快速上手，配置了vite.config.ts，tsconfig.json，.npmrc
2. 但是在组件中仍然无法获得nutui-uniapp中的组件库的类型提示
![image](https://github.com/user-attachments/assets/71a3f07b-9a24-42d4-b2d7-0ac1a50885e5)

3. 我恰好同时也配置了`@uni-helper/uni-app-types`,看到uni中的组件有类型提示，于是参考`node_modules/.pnpm/@uni-helper+uni-app-types@1.0.0-alpha.3_typescript@5.5.4_vue@3.4.37_typescript@5.5.4_/node_modules/@uni-helper/uni-app-types/dist/index.d.mts`中的内容，对`node_modules/nutui-uniapp/global.d.ts`作了修改：将

      ```ts
      declare module '@vue/runtime-core'
      ```
      改成
      ```ts
      declare module 'vue'
      ```
4. 同时将vscode插件`vue-official`从`2.0.28`降级到`2.0.26`
5. 最终获得到类型提示
![image](https://github.com/user-attachments/assets/dfb084e3-af35-44a8-8542-a8253f759457)

### 期望的结果是什么？

![image](https://github.com/user-attachments/assets/d290537a-b15c-46f0-9ea6-0cba12000b8f)

### 实际的结果是什么？

![image](https://github.com/user-attachments/assets/71a3f07b-9a24-42d4-b2d7-0ac1a50885e5)

### 环境信息

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 7840HS with Radeon 780M Graphics
    Memory: 10.20 GB / 27.69 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    nutui-uniapp: ^1.7.14 => 1.7.14

### 其他补充信息

vue版本:3.4.36
vite版本:5.3.5
vue-official版本:2.0.28(无法获得类型提示)2.0.26(配合上述中的操作可以)

**Comment by xiaohe0601** [comment]
参考 https://github.com/xiaohe0601/xiaohe-uniapp-next/tree/nutui 的配置，并且使用 volar `2.0.26`

**Comment by Caffeine19** [comment]
> 参考 https://github.com/xiaohe0601/xiaohe-uniapp-next/tree/nutui 的配置，并且使用 volar `2.0.26`

这个仓库里的东西太多太重了，请问有最简单的实现吗，舅舅孩子😭
请问是不是跟这个有关系 https://github.com/vuejs/pinia/discussions/2729

**Comment by yang1206** [comment]
> > 参考 [xiaohe0601/xiaohe-uniapp-next@`nutui`](https://github.com/xiaohe0601/xiaohe-uniapp-next/tree/nutui?rgh-link-date=2024-08-16T06%3A08%3A00Z) 的配置，并且使用 volar `2.0.26`
> 
> 这个仓库里的东西太多太重了，请问有最简单的实现吗，舅舅孩子😭 请问是不是跟这个有关系 [vuejs/pinia#2729](https://github.com/vuejs/pinia/discussions/2729)

经过测试, 最简单的方案应该就是按照文档配置，并将 volar 插件版本降级到`2.0.26`

**Comment by yang1206** [comment]
这个问题其实要向`@uni-helper/vite-plugin-uni-components`插件上游提一个 issue，将生成文件改为`declare module 'vue'`

**Comment by xiaohe0601** [comment]
更新 `nutui-uniapp` 至 `1.7.15`，并降级 volar 插件至 `2.0.26`

---

参考 https://github.com/nutui-uniapp/nutui-uniapp-simple-demo

**Comment by Caffeine19** [comment]
> 更新 `nutui-uniapp` 至 `1.7.15`，并降级 volar 插件至 `2.0.26`
> 
> 参考 https://github.com/nutui-uniapp/nutui-uniapp-simple-demo

试了下没有问题，非常感谢

**Comment by xiaohe0601** [comment]
> > 更新 `nutui-uniapp` 至 `1.7.15`，并降级 volar 插件至 `2.0.26`
> > 参考 https://github.com/nutui-uniapp/nutui-uniapp-simple-demo
> 
> 试了下没有问题，非常感谢 不过vscode感觉卡卡的😂

现在可以试试 volar `2.1.4` 了

**Comment by Caffeine19** [comment]
> > > 更新 `nutui-uniapp` 至 `1.7.15`，并降级 volar 插件至 `2.0.26`
> > > 参考 https://github.com/nutui-uniapp/nutui-uniapp-simple-demo
> > 
> > 
> > 试了下没有问题，非常感谢 不过vscode感觉卡卡的😂
> 
> 现在可以试试 volar `2.1.4` 了

可以，上周2.1.0还是2.1.2我试了下还是有问题的，2.1.4就很完美
