### ISSUE TITLE
nut-input-number组件编译成微信小程序Sass警告

### ISSUE THREAD

**Issue by huanggyao** [nutui-uniapp/nutui-uniapp#408]
### nutui-uniapp 版本号

1.7.15

### 平台

weapp

### 重现链接

使用nut-input-number组件，然后执行命令就会提示

### 重现步骤

执行npm run dev:mp-weixin
![nut-input-number](https://github.com/user-attachments/assets/21851b24-75d8-4caa-a2e6-1a7ad15d6a73)

### 期望的结果是什么？

不要出现Sass的警告问题

### 实际的结果是什么？

出现Sass警告问题

### 环境信息

win 11，Vue：3.4.21，nutui-uniapp：1.7.15，Sass：1.77.8，TS：5.5.3，Vite：5.2.8

**Comment by xiaohe0601** [comment]
感谢反馈，目前不影响实际表现，下一个小版本修复警告~
