### ISSUE TITLE
在tsconfig.json已经添加了types，但是组件ts类型显示还是unknown，用自动引入的方法也是没有起效

### ISSUE THREAD

**Issue by 1439437603** [nutui-uniapp/nutui-uniapp#41]
### uniapp-nutui 版本号

1.0.0

### 平台

其他小程序

### 重现链接

https://gitee.com/lzl1439437603/rabbit-vue3-ts-new

### 重现步骤

已经安装了Volar插件，版本对应"vue": "^3.2.47","nutui-uniapp": "^1.0.0",
1. pnpm add nutui-uniapp
2. 配置tsconfig.json，"types": ["nutui-uniapp/global.d.ts"]
3. 在vue文件中编写<nut-button type="primary"> 主要按钮 </nut-button>
4. 鼠标上移查看ts类型，显示为 unknown

### 期望的结果是什么？

可以查看正确的ts类型

### 实际的结果是什么？

鼠标上移查看ts类型，显示为 unknown

### 其他补充信息

查看了nutui-uniapp/global.d.ts, 也没啥问题，但是就是没类型提示，不知道为什么

**Comment by yang1206** [comment]
volar版本是多少

**Comment by 1439437603** [comment]
volar版本是1.8.8，很奇怪的是我刚才将tsconfig.ts中的"moduleResolution": "Node"改为duleResolution": "Node16就可以了"，现在还在查阅资料，看看是为什么，大佬要是知道也可以说一下

**Comment by 1439437603** [comment]
好吧，并没有完全生效，只是组件上移有相应的提示了，组件颜色变成正常的绿色而已。编写属性依旧没有提示

**Comment by yang1206** [comment]
```json
"include": [
    "node_modules/nutui-uniapp/global.d.ts"
]
```
加一行这个看看

**Comment by 1439437603** [comment]
> ```json
> "include": [
>     "node_modules/nutui-uniapp/global.d.ts"
> ]
> ```
> 
> 加一行这个看看

可以了，谢谢你，辛苦了

**Comment by Caffeine19** [comment]
> ```json
> "include": [
>     "node_modules/nutui-uniapp/global.d.ts"
> ]
> ```
> 
> 加一行这个看看

放在include貌似在.vue文件中会卡，ts的提示加载的很慢，我是放在compilerOptions/types里面，不影响速度

**Comment by m18318378952062** [comment]
你好，怎么解决的

**Comment by xiaohe0601** [comment]
> 你好，怎么解决的

https://github.com/nutui-uniapp/nutui-uniapp/issues/405#issuecomment-2323715006

**Comment by Caffeine19** [comment]
> 你好，怎么解决的

https://github.com/Caffeine19/uni-full-setup
可以参考下我这个仓库

1. vscode vue-official 插件 2.1.6
2. nutui-uniapp 更新到最新
3. typescript相关的包更新一下，可以参考package.json
4. 我这里用的是easycome的方式，unplugin容易卡，pages.json里配置一下，然后tsconfig.json里加入nutui-uniapp的组件类型

**Comment by Caffeine19** [comment]
https://github.com/Caffeine19/uni-full-setup
可以参考下我这个仓库

vscode vue-official 插件 2.1.6
nutui-uniapp 更新到最新
typescript相关的包更新一下，可以参考package.json
我这里用的是easycome的方式，unplugin容易卡，pages.json里配置一下，然后tsconfig.json里加入nutui-uniapp的组件类型
