### ISSUE TITLE
searchbar组件的click-left-icon和click-right-icon事件绑定问题

### ISSUE THREAD

**Issue by ZickCode** [nutui-uniapp/nutui-uniapp#416]
### nutui-uniapp 版本号

1.7.14

### 平台

其他小程序

### 重现链接

https://nutui-uniapp.pages.dev/components/dentry/searchbar.html

### 重现步骤

使用uniapp开发的微信小程序
searchbar组件的click-left-icon事件只绑定了leftout slots，而click-right-icon事件只绑定了rightout slots
![image](https://github.com/user-attachments/assets/2f229da3-94d9-41ec-838c-be1601027e6e)
![image](https://github.com/user-attachments/assets/c19bae75-969d-4d40-9c8a-809d32d5e99d)

### 期望的结果是什么？

要不就都绑上，要不就单独区分开，弄一个clickLeftInIcon，clickLeftOutIcon，right同理

### 实际的结果是什么？

事件绑定逻辑有问题，一个绑定在in，一个绑定在out

**Comment by yang1206** [comment]
这里需要一个breaking change，为每个icon 都加一个事件吧，最好还是 2.0 一起改动
