### ISSUE TITLE
[FR]导入阿里巴巴矢量图标库，自定义图标,无法在android或者ios上使用图标

### ISSUE THREAD

**Issue by Thinker-feiluo** [nutui-uniapp/nutui-uniapp#422]
### 这个功能解决了什么问题？

解决在android和ios上使用阿里巴巴自定义矢量图标库

### 你期望的组件设计是怎样的？

能够在android和ios上使用阿里巴巴自定义矢量图标库

**Comment by xiaohe0601** [comment]
怎么使用的？

**Comment by Thinker-feiluo** [comment]
> 怎么使用的？

和nutui-uniapp官网使用方法一致,从阿里巴巴矢量库下载到本地(下载的是/assets/font/iconfont.css)，然后引入到mian文件下，然后使用<nut-icon font-class-name="iconfont" class-prefix="icon" name="close" />来使用,
比如在别的项目中使用<span class="iconfont icon-love"> 
那么在untui中我是这样<nut-icon font-class-name="iconfont" class-prefix="icon" name="love" />
但是在Android和ios看不到那些图标，在h5运行中可以看到那些图标，这是为什么呢？

**Comment by Thinker-feiluo** [comment]
> 怎么使用的？

"<span class="iconfont icon-love">"
untui "<nut-icon font-class-name="iconfont" class-prefix="icon" name="love" />"

**Comment by xiaohe0601** [comment]
![image](https://github.com/user-attachments/assets/b6ae0522-addb-4489-a981-a43738fdf163)

未复现问题，请提供一个最小可复现仓库吧
