### ISSUE TITLE
Dialog 对话框visible=true时，其他组件显示错误

### ISSUE THREAD

**Issue by cqshenao** [nutui-uniapp/nutui-uniapp#432]
### nutui-uniapp 版本号

1.7.17

### 平台

alipay

### 重现链接

无

### 重现步骤

代码：
[新建 文本文档 (2).txt](https://github.com/user-attachments/files/17301348/2.txt)

### 期望的结果是什么？

![正常](https://github.com/user-attachments/assets/d161f890-f624-40a9-b01a-7a98e8cf1984)

### 实际的结果是什么？

![错误](https://github.com/user-attachments/assets/f1ee8d51-294a-4725-ab98-de16b4b2fd2c)

**Comment by xiaohe0601** [comment]
目前基于 `nut-popup` 的组件 `visible` 属性初始值为 `true` 时会丢失 `z-index`，下个版本会修复，临时解决方案：
1. 将 `visible` 初始值设置为 `false`
2. 或者手动指定 `z-index` 属性
