### ISSUE TITLE
useDialog onMounted 中未使用条件编译,导致小程序平台报错

### ISSUE THREAD

**Issue by BlueCat918** [nutui-uniapp/nutui-uniapp#433]
### nutui-uniapp 版本号

1.7.17

### 平台

其他小程序

### 重现链接

https://github.com/nutui-uniapp/nutui-uniapp/blob/5c366650dc87bc933aa6d297b8a9d4f4c6a8b21e/packages/nutui/components/dialog/use-dialog.ts#L49

### 重现步骤

引入Dialog组件

### 期望的结果是什么？

不出现 TypeError 的错误

### 实际的结果是什么？

报错: TypeError: Cannot read property 'addEventListener' of undefined

**Comment by xiaohe0601** [comment]
感谢反馈，下个版本修复
