### ISSUE TITLE
表单--nut-form-item-body-slots-text-align不起作用

### ISSUE THREAD

**Issue by cqshenao** [nutui-uniapp/nutui-uniapp#444]
### nutui-uniapp 版本号

1.8.1

### 平台

alipay

### 重现链接

无

### 重现步骤

![image](https://github.com/user-attachments/assets/5c574bd4-228e-453b-aab5-41b3c850c9a3)
<view class="nut-form-item__body__slots" style="text-align:left;"><component is="node-modules/nutui-uniapp/components/avatar/avatar" uS="[object Array]" uI="0d22a2f2-3,0d22a2f2-2" uP="51,0,1" onVI="__l"><view class="nut-avatar nut-avatar-round" style="background-color:#eee;color:#666;width:80px;height:80px;"><image src="https://thirdwx.qlogo.cn/mmopen/vi_32/PiajxSqBRaEJW7Gebb7PZB6yG5cLEJa0ibmCtkcTwdlqARVomXaH3ZlaRbd7864IDlicJ5gAV8MicgsHYKIdBYDIh8icLuaic18ic1QA6GAE7PWdfibM30PxGlbebQ/132"></image></view></component></view>
![1730967947380](https://github.com/user-attachments/assets/afc72e87-4aac-48a4-92b8-62f21b4981b6)
![image](https://github.com/user-attachments/assets/7e0d3d39-9525-48c0-8ea2-4804afdc3c7f)

### 期望的结果是什么？

图片居中

### 实际的结果是什么？

图片没有居中

**Comment by xiaohe0601** [comment]
通过 `body-align` 属性控制
