### ISSUE TITLE
文档商品卡片点击404了

### ISSUE THREAD

**Issue by Yer11214** [nutui-uniapp/nutui-uniapp#47]
### uniapp-nutui 版本号

1.0.0

### 平台

h5

### 重现链接

https://www.uniapp-nutui.tech/components/business/card.html

### 重现步骤

地址[https://www.uniapp-nutui.tech/components/business/card.html](地址链接)

### 期望的结果是什么？

无

### 实际的结果是什么？

无

**Comment by yang1206** [comment]
<img width="1512" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/28709596/8aa7f59e-84b7-4687-8340-6e23d70c539a">

我这里看是正常的啊

**Comment by yang1206** [comment]
你好，请问你有没有兴趣一起来维护这个库

**Comment by Yer11214** [comment]
> 你好，请问你有没有兴趣一起来维护这个库

可以的！我现在在用这个库做项目，如果我发现了问题，并且我自己可以改的话我会提交pr的，如果没时间的话我就提issues啦

**Comment by yang1206** [comment]
> > 你好，请问你有没有兴趣一起来维护这个库
> 
> 可以的！我现在在用这个库做项目，如果我发现了问题，并且我自己可以改的话我会提交pr的，如果没时间的话我就提issues啦

请查看你的消息，我重新邀请了

**Comment by Yer11214** [comment]
我这边没有收到 = 。=

**Comment by Yer11214** [comment]
> > > 你好，请问你有没有兴趣一起来维护这个库
> > 
> > 
> > 可以的！我现在在用这个库做项目，如果我发现了问题，并且我自己可以改的话我会提交pr的，如果没时间的话我就提issues啦
> 
> 请查看你的消息，我重新邀请了
没有收到 =。=
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/39794167/619a19af-bb49-452c-b847-bcf78cf5640a)

**Comment by yang1206** [comment]
你再看一下

**Comment by Yer11214** [comment]
> 你再看一下

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/39794167/42c6859d-cb35-46c2-b737-f0409b6f1ca4)
还是接收不到 = = 

+v吧用base64解密一下这个   WWVyMTEyMTQ=

**Comment by xiaohe0601** [comment]
可以看看你github绑定的邮箱，里面应该有封邀请邮件 @Yer11214

**Comment by Yer11214** [comment]
> 可以看看你github绑定的邮箱，里面应该有封邀请邮件 @Yer11214

可能我之前邮箱有问题了，我切换了邮箱 在邀请我一下吧！

**Comment by xiaohe0601** [comment]
[点击这个](https://github.com/orgs/nutui-uniapp/invitation?via_email=1) @Yer11214

**Comment by Yer11214** [comment]
> [点击这个](https://github.com/orgs/nutui-uniapp/invitation?via_email=1) @Yer11214

加入了！ 感谢
