### ISSUE TITLE
支付宝小程序不支持?? 等链式操作符

### ISSUE THREAD

**Issue by blakelu** [nutui-uniapp/nutui-uniapp#48]
### uniapp-nutui 版本号

1.1.1

### 平台

alipay

### 重现链接

无

### 重现步骤

使用nut-picker组件, 支付宝小程序编译报错
<img width="331" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/13463232/8e5e4197-5f4c-422f-9c1d-c379ad8c6373">

### 期望的结果是什么？

在支付宝小程序下正常运行

### 实际的结果是什么？

无法编译支付宝小程序

### 环境信息

 System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 91.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.4

**Comment by yang1206** [comment]
已修复，请更新最新版
