### ISSUE TITLE
[FR]: 希望所有组件都能套入外层class

### ISSUE THREAD

**Issue by leecn-web** [nutui-uniapp/nutui-uniapp#49]
### 这个功能解决了什么问题？

因为几乎所有项目的样式都有略微的差别,而目前组件上提供的无法满足正常的项目需求,自定义样式很麻烦.所以能不能提供一个class的props套在组件的最外层,或者像antd的modal一样,提供一个className和一个wrapClassName.这样开发者自定义样式就非常方便了.

### 你期望的组件设计是怎样的？

props: {
  className: 'xxx'
}

component: {
  class="nutui-xxx" :class="className"
}

**Comment by yang1206** [comment]
https://www.uniapp-nutui.tech/guide/theme.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E7%9A%84-style-%E6%88%96-class
