### ISSUE TITLE
1.1.2版本报错，无法安装

### ISSUE THREAD

**Issue by cqzhong** [nutui-uniapp/nutui-uniapp#50]
### uniapp-nutui 版本号

1.1.2

### 平台

h5

### 重现链接

无

### 重现步骤

yarn add nutui-uniapp@1.1.2

![181694141585_ pic_hd](https://github.com/nutui-uniapp/nutui-uniapp/assets/10128830/7be5e792-b126-4822-9b16-53b55b0a3340)

### 期望的结果是什么？

能正常安装版本1.1.2

### 实际的结果是什么？

安装报错

**Comment by yang1206** [comment]
提供最小复现，截图没头没尾的，什么都看不出来

**Comment by cqzhong** [comment]
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/10128830/a9f5ae55-59c6-4335-8cc6-843dca421f74)

**Comment by yang1206** [comment]
> ![image](https://user-images.githubusercontent.com/10128830/266494438-a9f5ae55-59c6-4335-8cc6-843dca421f74.png)

安装1.1.3试试
