### ISSUE TITLE
nut-list 虚拟列表异常

### ISSUE THREAD

**Issue by wen-bug** [nutui-uniapp/nutui-uniapp#51]
### nutui-uniapp 版本号

^1.0.0

### 平台

weapp

### 重现链接

https://juejin.cn/post/7276324625838964796

### 重现步骤

自封装组件导入nut-list     index引用自定义组件 Component is not found in path "node-modules/nutui-uniapp/components/list/list"

### 期望的结果是什么？

正常显示文档例子

### 实际的结果是什么？

Component is not found in path "node-modules/nutui-uniapp/components/list/list" (using by "components/scrollLists/scrollLists")(env: Windows,mp,1.06.2309072; lib: 3.0.1)

### 环境信息

    "nutui-uniapp": "^1.0.0",
    "pinia": "2.0.36",
    "sass": "^1.66.1",
    "sass-loader": "^13.3.2",
    "vue": "^3.2.45",

**Comment by yang1206** [comment]
请提供最小重现工程

**Comment by wen-bug** [comment]
今天创了新项目可以正常使用，再启动老项目nut-list又能渲染了，无法重现了
&nbsp;


天宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月8日(星期五) 晚上9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nutui-uniapp/nutui-uniapp] nut-list 虚拟列表异常 (Issue #51)





 
请提供最小重现工程

**Comment by yang1206** [comment]
请提供报错项目

**Comment by wen-bug** [comment]
wen-bug/wx-shop (github.com)&nbsp; 目前正常 恢复正常渲染前 操作 ***@***.***/vite-plugin-uni-components&nbsp;nutui-uniapp
&nbsp;


天宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月9日(星期六) 下午2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nutui-uniapp/nutui-uniapp] nut-list 虚拟列表异常 (Issue #51)





 
请提供报错项目
