### ISSUE TITLE
Elevator 电梯楼层有问题

### ISSUE THREAD

**Issue by tsliangyonghui** [nutui-uniapp/nutui-uniapp#52]
### nutui-uniapp 版本号

1.1.3

### 平台

h5

### 重现链接

https://www.uniapp-nutui.tech/components/nav/elevator.html

### 重现步骤

    <nut-elevator :index-list="dataList" :height="260"></nut-elevator>

### 期望的结果是什么？

在索引条只有点击有用，滑动也应该有效果

### 实际的结果是什么？

在索引条上手机滑动没有效果
function touchMove(e: TouchEvent) {
  const firstTouch = e.touches[0]
  state.touchState.y2 = firstTouch.pageY
  const delta = ((state.touchState.y2 - state.touchState.y1) / spaceHeight) | 0
  state.codeIndex = state.anchorIndex + delta
  scrollTo(state.currentIndex)
}可能有问题

**Comment by yang1206** [comment]
什么没有效果，说清楚问题，请补充问题信息
