### ISSUE TITLE
nut-uploader

### ISSUE THREAD

**Issue by yangyaru0108** [nutui-uniapp/nutui-uniapp#57]
### nutui-uniapp 版本号

1.1.4

### 平台

weapp

### 重现链接

暂无

### 重现步骤

<nut-uploader v-model:file-list="pageData.fileList" :maximum="3" :auto-upload="false">
    <template v-slot:uploadIcon>
        <NutIcon name="photograph" custom-color="#808080" />
        <view class="text-999 font-size-10 lh-12">上传图片</view>
        <view class="text-999 font-size-10 lh-12">
            {{ '(' + pageData.fileList.length + '/' + 3 + ')' }}
        </view>
    </template>
</nut-uploader>

### 期望的结果是什么？

现在的版本
<slot name="upload-icon">
  <NutIcon name="photograph" custom-color="#808080" />
</slot>
改为 uploadIcon 才能生效
<slot name="upload-icon">
  <NutIcon name="photograph" custom-color="#808080" />
</slot>

### 实际的结果是什么？

自定义的插槽不生效

**Comment by yang1206** [comment]
请补充问题详情，重现步骤
