### ISSUE TITLE
(cascader) 动态加载标题

### ISSUE THREAD

**Issue by clarehjh** [nutui-uniapp/nutui-uniapp#60]
### nutui-uniapp 版本号

1.1.6

### 平台

weapp

### 重现链接

https://www.uniapp-nutui.tech/components/dentry/cascader.html

### 重现步骤

(cascader) 动态加载标题虽然能够动态展示标题了，当选项字段长的话会导致上方的标题，无法滑动显示选择下一步的标题，需要手动滑动到指定位置，才能显示请选择
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/83281667/0bf78bf1-e707-411b-9635-b18f00cb74ac)

### 期望的结果是什么？

正常我顶下一步应该是这样：
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/83281667/6de132ff-1a3e-4b7f-b585-1a5a16a28c21)

### 实际的结果是什么？

同上

### 环境信息

  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 1.14 GB / 15.69 GB
  Binaries:
    Node: 18.17.0 - D:\nodejs\node.EXE
    npm: 9.6.7 - D:\nodejs\npm.CMD
    pnpm: 8.6.10 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.31)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    nutui-uniapp: ^1.1.6 => 1.1.6 

### 其他补充信息

无

**Comment by yang1206** [comment]
标题过长，覆盖掉标题的样式即可
```scss
::v-deep .nut-cascader .nut-tabs__titles-item {
  white-space: normal;
  max-width: 120px;
}
```

**Comment by yang1206** [comment]
`v1.1.7` 增加了对cascader 标题的[配置选项](https://www.uniapp-nutui.tech/components/dentry/cascader.html#props)
