### ISSUE TITLE
avatar type errors

### ISSUE THREAD

**Issue by ModyQyW** [nutui-uniapp/nutui-uniapp#62]
### nutui-uniapp 版本号

1.1.7

### 平台

weapp

### 重现链接

https://github.com/MillCloud/presets/tree/main/uni-app

### 重现步骤

```shell
# 启用 corepack
npm install --location=global --force corepack
corepack enable
# 克隆仓库
npx tiged MillCloud/presets/uni-app test-uni-app
# 进入目录
cd test-uni-app
# 安装依赖
npm install --force
# 检查类型
npm run check:types
```

### 期望的结果是什么？

无报错

### 实际的结果是什么？

<img width="969" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/31850793/2d340ddb-53a1-4689-914d-33d07fdb5c2f">

### 环境信息

<img width="769" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/31850793/b549536c-4930-4b45-8417-9d156ae141e1">

### 其他补充信息

<img width="411" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/31850793/c8921c0a-055d-4576-9870-c0a04ce51055">

感谢作者的努力！

**Comment by yang1206** [comment]
thanks ！
