### ISSUE TITLE
dialog按钮样式存在问题

### ISSUE THREAD

**Issue by mingliangcheng** [nutui-uniapp/nutui-uniapp#64]
### nutui-uniapp 版本号

1.1.8

### 平台

weapp

### 重现链接

<nut-dialog title="xxx" content="xxxxxx" v-model:visible="deleteVisible" @cancel="onCancel" @ok="onOk" />

### 重现步骤

**按照官方文档教程，微信小程序中使用dialog弹窗，底部按钮样式变形**

### 期望的结果是什么？

**期望如图所示，底部按钮正常显示**
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/76807344/6aab94cb-b071-457f-bbf4-1557f1a22336)****

### 实际的结果是什么？

**实际结果**
![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/76807344/7c9efaee-f10e-40d9-bdc1-0a8ca3efe4d0)

**Comment by yang1206** [comment]
请提供复现工程
