### ISSUE TITLE
[FR]: 项目启动报错

### ISSUE THREAD

**Issue by quarkcms** [nutui-uniapp/nutui-uniapp#66]
### 这个功能解决了什么问题？

Sourcemap for "E:/develop/quark/quark-uniapp/node_modules/vite/dist/client/client.mjs" points to missing source files​
​Sourcemap for "E:/develop/quark/quark-uniapp/node_modules/vite/dist/client/env.mjs" points to missing source files​
Cannot read properties of undefined (reading 'length')
12:49:16 [vite] Cannot read properties of undefined (reading 'length')
12:49:36 [vite] Cannot read properties of undefined (reading 'length') (x2)

### 你期望的组件设计是怎样的？

Sourcemap for "E:/develop/quark/quark-uniapp/node_modules/vite/dist/client/client.mjs" points to missing source files​
​Sourcemap for "E:/develop/quark/quark-uniapp/node_modules/vite/dist/client/env.mjs" points to missing source files​
Cannot read properties of undefined (reading 'length')
12:49:16 [vite] Cannot read properties of undefined (reading 'length')
12:49:36 [vite] Cannot read properties of undefined (reading 'length') (x2)

**Comment by yang1206** [comment]
请提供错误复现工程

**Comment by quarkcms** [comment]
https://github.com/quarkcms/quark-uniapp

**Comment by yang1206** [comment]
<style lang="scss">
@import 'nutui-uniapp/styles/index';
</style>

**Comment by quarkcms** [comment]
这里要去掉吗？

**Comment by quarkcms** [comment]
文档上有这个

**Comment by yang1206** [comment]
改成这样，你漏了 lang="scss"

**Comment by huaerss** [comment]
我的有scss 也会报错Sourcemap for "E:/SVNfiles/jiaozu/RentPay-Uni/landlord/node_modules/.pnpm/nutui-uniapp@1.6.6_@uni-helper+uni-app-types@0.5.12_vue@3.2.47/node_modules/nutui-uniapp/components/tabs/hooks.ts" points to missing source files​
Sourcemap for "E:/SVNfiles/jiaozu/RentPay-Uni/landlord/node_modules/.pnpm/nutui-uniapp@1.6.6_@uni-helper+uni-app-types@0.5.12_vue@3.2.47/node_modules/nutui-uniapp/components/tabs/tabs.ts" points to missing source files​
而且是多条  是使用了 @uni-helper/vite-plugin-uni-components 才有的 不用就没事
