### ISSUE TITLE
组件库官网文档挂了，访问不了

### ISSUE THREAD

**Issue by cg123456** [nutui-uniapp/nutui-uniapp#68]
### nutui-uniapp 版本号

1.00

### 平台

h5

### 重现链接

官网文档地址访问不了

### 重现步骤

官网文档地址访问不了

### 期望的结果是什么？

官网文档地址访问不了

### 实际的结果是什么？

官网文档地址访问不了

### 其他补充信息

官网文档地址访问不了

**Comment by yang1206** [comment]
文档部署在vercel中，vercel最近彻底被墙，暂时请自备梯子

**Comment by yang1206** [comment]
请访问新地址 https://nutui-uniapp.netlify.app/
