### ISSUE TITLE
address-list组件小程序端，del和edit事件无法阻止冒泡

### ISSUE THREAD

**Issue by Lazy-Hand** [nutui-uniapp/nutui-uniapp#69]
### nutui-uniapp 版本号

1.1.5

### 平台

weapp

### 重现链接

<template>   <nut-address-list     :data="data"     @click-item="clickItem"     @del-icon="delClick"     @edit-icon="editClick"     :show-bottom-button="false"     :options="dataOptions"   >   </nut-address-list> </template> <script lang="ts"> import { ref, reactive } from 'vue'; export default {   setup() {     const data = ref([       {         testid:3,         testaddressName:'姓名',         phone:'123****4567',         defaultAddress:false,         fullAddress:'北京市通州区测试测试测试测试测试测试测试测试测试'       },       {         testid:4,         testaddressName:'姓名',         phone:'123****4567',         defaultAddress:true,         fullAddress:'北京市通州区测试测试测试测试测试测试测试测试测试'       },     ]);     const dataOptions = reactive({       id: 'testid',       addressDetail:'testaddressDetail',       addressName:'testaddressName'     });     const clickItem = ()=>{       console.log('Click To Address');     }     const delClick = ()=>{       console.log('Click To Delete');     }     const editClick = ()=>{       console.log('Click To Edit');     }     return {       data,       clickItem,       delClick,       editClick,       dataOptions     };   } }; </script>

### 重现步骤

<template>
  <nut-address-list
    :data="data"
    @click-item="clickItem"
    @del-icon="delClick"
    @edit-icon="editClick"
    :show-bottom-button="false"
    :options="dataOptions"
  >
  </nut-address-list>
</template>
<script lang="ts">
import { ref, reactive } from 'vue';
export default {
  setup() {
    const data = ref([
      {
        testid:3,
        testaddressName:'姓名',
        phone:'123****4567',
        defaultAddress:false,
        fullAddress:'北京市通州区测试测试测试测试测试测试测试测试测试'
      },
      {
        testid:4,
        testaddressName:'姓名',
        phone:'123****4567',
        defaultAddress:true,
        fullAddress:'北京市通州区测试测试测试测试测试测试测试测试测试'
      },
    ]);
    const dataOptions = reactive({
      id: 'testid',
      addressDetail:'testaddressDetail',
      addressName:'testaddressName'
    });
    const clickItem = ()=>{
      console.log('Click To Address');
    }
    const delClick = ()=>{
      console.log('Click To Delete');
    }
    const editClick = ()=>{
      console.log('Click To Edit');
    }
    return {
      data,
      clickItem,
      delClick,
      editClick,
      dataOptions
    };
  }
};
</script>

### 期望的结果是什么？

两个图标阻止冒泡

### 实际的结果是什么？

未实现阻止冒泡，小程序不能使用event.stopPropagation();，组件内部应该使用.stop

**Comment by yang1206** [comment]
v1.1.9已修复
