### ISSUE TITLE
Rollup 无法找到side-navbaritem组件

### ISSUE THREAD

**Issue by wen-bug** [nutui-uniapp/nutui-uniapp#70]
### nutui-uniapp 版本号

1.1.8

### 平台

weapp

### 重现链接

https://github.com/wen-bug/wx-shop

### 重现步骤

![IQU51NIH LP9JOAD2T6A2B](https://github.com/nutui-uniapp/nutui-uniapp/assets/56168055/0760b04f-0702-4bcd-9d0a-d1350964a13b)
示例模板无法使用

### 期望的结果是什么？

正常显示示例

### 实际的结果是什么？

![FB@ 5`MDU02$ 3KA4_20ZVD](https://github.com/nutui-uniapp/nutui-uniapp/assets/56168055/3a0ab1bc-7dd6-42e5-b075-29e5bb6683b5)
![P6Q{)~%W8E_J3P_%DXZ20PU](https://github.com/nutui-uniapp/nutui-uniapp/assets/56168055/0fc416d3-078e-48c9-9a8a-8bbee919a47d)

无法找到nut-side-navbar-item

**Comment by yang1206** [comment]
暂时可以先这样使用`<nut-side-navbaritem />`  `nut-sub-sidenavbar`

**Comment by yang1206** [comment]
更新了使用文档，请[查看](https://nutui-uniapp.netlify.app/components/nav/sidenavbar.html)
