### ISSUE TITLE
标签的ts类型报错

### ISSUE THREAD

**Issue by CLD5186** [nutui-uniapp/nutui-uniapp#71]
### nutui-uniapp 版本号

1.1.10

### 平台

h5, 其他小程序

### 重现链接

暂无

### 重现步骤

按照官方提供的快速上手指引进行配置搭建。最后普通的标签报错.
![WeChat20809bdb44475ce1181df679c2092da1](https://github.com/nutui-uniapp/nutui-uniapp/assets/21166810/51ab929b-bd95-4083-97a8-a109063f7eab)
初步发现，好像是无法识别view这个标签。使用其他标签或者html标签都不会报错。

### 期望的结果是什么？

无报错

### 实际的结果是什么？

报错咯

**Comment by yang1206** [comment]
这和组件库没什么关系，请尝试切换 volar 插件版本

**Comment by HalseySpicy** [comment]
@uni-helper/vite-plugin-uni-components 插件影响的，删除即可

**Comment by xiaohe0601** [comment]
安装 [@uni-helper/uni-app-types](https://github.com/uni-helper/uni-app-types)，并按照 [文档](https://github.com/uni-helper/uni-app-types?tab=readme-ov-file#%E9%85%8D%E7%BD%AE) 配置即可
