### ISSUE TITLE
使用 vite4 + vue3+ uniapp 会报这个错误 

### ISSUE THREAD

**Issue by JS-mark** [nutui-uniapp/nutui-uniapp#72]
### nutui-uniapp 版本号

1.1.10

### 平台

h5, weapp

### 重现链接

https://github.com/JS-mark/uni-app-demo

### 重现步骤

正常安装

### 期望的结果是什么？

协助排查下这个问题，不在出现此类输出

### 实际的结果是什么？

协助排查下这个问题，不在出现此类输出

### 环境信息

  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 6.22 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.70
    Safari: 17.0
  npmPackages:
    nutui-uniapp: ^1.1.10 => 1.1.10

### 其他补充信息

vue 3.2.47
vite 4.1.4
node 18.x

**Comment by JS-mark** [comment]
<img width="1159" alt="image" src="https://github.com/nutui-uniapp/nutui-uniapp/assets/31335385/89297a9f-2b51-49fc-b120-5c2a85d06e2a">

**Comment by yang1206** [comment]
你提供的示例无法正常启动

**Comment by yang1206** [comment]
升级 vite 版本即可
