### ISSUE TITLE
Elevator 电梯楼层在h5中正常，安卓app中点击右侧索引无效，滑动内容的时候，索引也不会跟随切换

### ISSUE THREAD

**Issue by weixl9451** [nutui-uniapp/nutui-uniapp#73]
### nutui-uniapp 版本号

1.1.10

### 平台

其他小程序

### 重现链接

暂无

### 重现步骤

官方示例

### 期望的结果是什么？

可以在app使用

### 实际的结果是什么？

不能使用

**Comment by yang1206** [comment]
暂时未在 app 中测试过，请提供复现工程

**Comment by weixl9451** [comment]
> 暂时未在 app 中测试过，请提供复现工程
使用的就是Elevator 电梯楼层官方示例里的基础用法的代码，通过hbuilder x运行到Android App基座

**Comment by RJQingHuan** [comment]
+1

**Comment by RJQingHuan** [comment]
我看了一下,好像是因为dataset在app中获取不到的原因
