### ISSUE TITLE
NumberKeyboard组件在type="rightColumn"时，某些版本安卓机无法正常显示

### ISSUE THREAD

**Issue by 749106618** [nutui-uniapp/nutui-uniapp#78]
### nutui-uniapp 版本号

1.1.10

### 平台

其他小程序

### 重现链接

暂无

### 重现步骤

官方示例

### 期望的结果是什么？

与官方示例一致

### 实际的结果是什么？

完成按钮和删除按钮 样式失效

### 环境信息

android版本：10
手机: oppo find x

### 其他补充信息

inset属性问题，改成正常写法没问题，还请解决一下

**Comment by yang1206** [comment]
请提供复现工程

**Comment by 749106618** [comment]
就是官方示例的代码，用个低版本安卓机就是复现，那个inset属性确实没法兼容一些安卓机

**Comment by yang1206** [comment]
v1.2.1已修复

**Comment by 749106618** [comment]
好的
