### ISSUE TITLE
nut-tabs 中的内容如果是异步的或者动态改变的，设置autoheight属性会导致nut-tab-pane高度一直为0

### ISSUE THREAD

**Issue by 2509989976** [nutui-uniapp/nutui-uniapp#83]
### nutui-uniapp 版本号

1.2.1

### 平台

h5, weapp

### 重现链接

暂无

### 重现步骤

```
<script setup lang="ts">
const content=ref("")
setTimeout(()=>{
  for(int i=0;i<100;i++){
    content.value+="测试文字测试文字"
  }
},3000)
</script>

<template>
  <nut-tabs v-model="tabIndex" >
    <nut-tab-pane title="文字内容">
      {{content}}
    </nut-tab-pane>
  </nut-tabs>
</template>

```

### 期望的结果是什么？

高度能够实时根据内容高度自动变化，或者提供一个可手动更新高度的Methods

### 实际的结果是什么？

动态变化内容后，高度始终为0

**Comment by yang1206** [comment]
设置 auto-height 必须设置 pane-key

**Comment by wangyesheng** [comment]
@yang1206 我设置了 pane-key 还是不行，初始化渲染的时候第一项 nut-tab-pane 始终还是 inactive

<img width="1209" height="586" alt="Image" src="https://github.com/user-attachments/assets/e0609224-aab7-41fe-9895-7f7b39fb60b6" />

<img width="1460" height="1442" alt="Image" src="https://github.com/user-attachments/assets/f6a65c17-35a5-43e6-8db5-d50c9b6ee950" />

<img width="3071" height="1836" alt="Image" src="https://github.com/user-attachments/assets/79d5fcd3-2460-41b5-9c59-6dd905c02e6c" />
