### ISSUE TITLE
[FR]: 关于input的问题。

### ISSUE THREAD

**Issue by CLD5186** [nutui-uniapp/nutui-uniapp#85]
### 这个功能解决了什么问题？

![WeChat7673ef5f09f4fbd74dc7413edb83dbaf](https://github.com/nutui-uniapp/nutui-uniapp/assets/21166810/e79614f6-aaa7-48af-8d00-b78b9a4a5b5a)
在使用nut-input组件的时候，发现组件默认有一个padding:10px 25px的内边距。而我的设计稿需要一个四周的边框。但是我不希望使用这个padding:10px 25px的值。但是我无法修改这个。我尝试使用custom-style属性。我发现它只作用到最里层的input标签上。

### 你期望的组件设计是怎样的？

希望能够自定义外层的内边距

**Comment by yang1206** [comment]
可以用:deep(.nut-input)

**Comment by CLD5186** [comment]
@yang1206 我重新起了一个项目，按照你的方式微信小程序上确实没有效果
