### ISSUE TITLE
[FR]: 只支持微信和支付宝小程序吗？其他平台的小程序支持吗？

### ISSUE THREAD

**Issue by momtboy** [nutui-uniapp/nutui-uniapp#89]
### 这个功能解决了什么问题？

支持其他平台小程序

### 你期望的组件设计是怎样的？

支持其他平台小程序

**Comment by yang1206** [comment]
理论上 uniapp 支持的小程序应该是都支持，但是其他平台的小程序我没有测试过， 可能会有一点小问题，如果你遇到问题再来这里提一个 issue

**Comment by wJinDou** [comment]
使用支付宝h5打开官方的案例页面[https://nutui-uniapp.netlify.app/ui/#/](url)，是没有任何展示的。是否不支持支付宝h5
