### ISSUE TITLE
Uploader能否加入图像上传前的crop剪裁功能 

### ISSUE THREAD

**Issue by yinSing** [nutui-uniapp/nutui-uniapp#91]
### 这个功能解决了什么问题？

Uploader能否加入图像上传前的crop剪裁功能 

### 你期望的组件设计是怎样的？

Uploader能否加入图像上传前的crop剪裁功能

**Comment by yang1206** [comment]
暂时没有时间增加新组件，如果你有兴趣可以查看对应分支修改一下，现在是不可用的状态
