### ISSUE TITLE
[FR]: 新增一个select下拉框组件

### ISSUE THREAD

**Issue by wgh4318** [nutui-uniapp/nutui-uniapp#92]
### 这个功能解决了什么问题？

移动端下拉选择与展示更加直接简洁

### 你期望的组件设计是怎样的？

类似uni-app的下拉输入框

**Comment by yang1206** [comment]
我个人认为移动端下拉框并不直观，picker 是更好的选择。目前的的目标是尽量与nutui for taro 保持一致，如果你需要 这个组件，欢迎你提一个 pr
