### ISSUE TITLE
pm package 1.3.2 publish incorrect

### ISSUE THREAD

**Issue by aliuq** [nutui-uniapp/nutui-uniapp#93]
### nutui-uniapp 版本号

1.3.2

### 平台

weapp

### 重现链接

Unknown

### 重现步骤

![image](https://github.com/nutui-uniapp/nutui-uniapp/assets/11707934/5bf0f95b-9dfc-40b3-8405-ff734a51da34)

### 期望的结果是什么？

Correct

### 实际的结果是什么？

Incorrect

**Comment by aliuq** [comment]
将 `package.json` 和 `example/package.json` 设置 `"private": true`，接着执行 `pnpm -r publish --access public` 命令对所有权限为公开的包进行发布，或者对单个包进行发布 `pnpm -F nutui-uniapp publish`

**Comment by yang1206** [comment]
抱歉，上次发布忘记切换目录了

**Comment by yang1206** [comment]
已经发布新版
