### ISSUE TITLE
[FR]: 你好，开发文档一直打不开。地址：https://nutui-uniapp.netlify.app/guide/quick-start.html或者https://nutui-uniapp.netlify.app/都打不开

### ISSUE THREAD

**Issue by hqhhtzj** [nutui-uniapp/nutui-uniapp#98]
### 这个功能解决了什么问题？

你好，开发文档一直打不开。地址：https://nutui-uniapp.netlify.app/guide/quick-start.html或者https://nutui-uniapp.netlify.app/都打不开

### 你期望的组件设计是怎样的？

你好，开发文档一直打不开。地址：https://nutui-uniapp.netlify.app/guide/quick-start.html或者https://nutui-uniapp.netlify.app/都打不开

**Comment by yang1206** [comment]
我这里可以正常打开，请检查你的网络或者自备一个梯子
